//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCAdPlacement.h"

@class NSString;

@interface SCAutoAdvanceAdsPlacement : NSObject <SCAdPlacement>
{
    NSString *_adRequestClientId;
    NSString *_inventoryId;
    NSString *_adUnitId;
    long long _position;
}

- (void).cxx_destruct;
- (double)adRequestTimeoutSeconds;
- (id)adRequestClientId;
- (id)type;
- (id)adPageImpressionDurationKey;
- (id)targetingParams;
- (id)key;
- (id)adUnitId;
- (id)initWithRequestId:(id)arg1 position:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

