//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIFont, UILabel;

@interface SCBadgeView : UIView
{
    UILabel *_titleLabel;
    UIFont *_defaultFont;
    long long _badgeCount;
}

@property(nonatomic) long long badgeCount; // @synthesize badgeCount=_badgeCount;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)tintColorDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

@end

