//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface SCBandwidthClassificationStats : NSObject
{
    NSObject<OS_dispatch_queue> *_bandwidthClassificationStatsQueue;
    NSMutableDictionary *_classificationResults;
}

+ (id)shared;
@property(retain, nonatomic) NSMutableDictionary *classificationResults; // @synthesize classificationResults=_classificationResults;
- (void).cxx_destruct;
- (void)reset;
- (id)getClassificationResults;
- (void)addClassificationResults:(id)arg1;
- (id)init;

@end

