//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBTweakObserver.h"

@class FBTweak, NSString;

@interface SCBroadcastTweaks : NSObject <FBTweakObserver>
{
    FBTweak *_storyRedesignTweak;
    FBTweak *_subscriptionTweak;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)tweakDidChange:(id)arg1;
- (void)tweaks;
- (_Bool)isReorderingEnabled;
- (_Bool)isAtoZChromeEnabled;
- (_Bool)isLiveStoryChromeEnabled;
- (_Bool)isTurnVolumeBackOffEnabled;
- (double)fadeSoundPromptDelay;
- (_Bool)isFadeSoundPromptEnabled;
- (_Bool)isPromptUserForSoundOnLiveStoriesEnabled;
- (_Bool)isPromptUserForSoundOnFriendStoriesEnabled;
- (long long)subscribeLongformFadeOutTimeMs;
- (long long)autoAdvanceRemindTooltipTimeInterval;
- (double)autoAdvanceAnimationDelay;
- (double)autoAdvanceAnimationTime;
- (_Bool)isAutoAdvanceAnimationEaseOut;
- (_Bool)isSlowerTapToSkipEnabled;
- (_Bool)isDDLEnabled;
- (_Bool)isSDLEnabled;
- (_Bool)isSEEnabled;
- (_Bool)isOperaEnabledForDiscover;
- (_Bool)isSubscriptionsEnabled;
- (_Bool)isStoryRedesignEnabled;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

