//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SCCameraTimerBlackBorderLayer, SCCameraTimerGradientLayer, SCCameraTimerRedCircleLayer, SCCameraTimerWhiteAndRedBorderLayer, UIImageView;

@interface SCCameraTimer : UIView
{
    SCCameraTimerGradientLayer *_gradientLayer;
    SCCameraTimerWhiteAndRedBorderLayer *_whiteAndRedBorderLayer;
    SCCameraTimerBlackBorderLayer *_blackBorderLayer;
    SCCameraTimerRedCircleLayer *_redCircleLayer;
    _Bool _isAnimating;
    double _dimAlpha;
    double _preRecordAnimationTime;
    double _initialCircleWidth;
    double _deltaCircleWidth;
    double _maxRecordingLength;
    UIImageView *_lensImageView;
}

@property(readonly, nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(readonly, nonatomic) UIImageView *lensImageView; // @synthesize lensImageView=_lensImageView;
@property(readonly, nonatomic) double maxRecordingLength; // @synthesize maxRecordingLength=_maxRecordingLength;
@property(readonly, nonatomic) double deltaCircleWidth; // @synthesize deltaCircleWidth=_deltaCircleWidth;
@property(readonly, nonatomic) double initialCircleWidth; // @synthesize initialCircleWidth=_initialCircleWidth;
@property(nonatomic) double preRecordAnimationTime; // @synthesize preRecordAnimationTime=_preRecordAnimationTime;
- (void).cxx_destruct;
- (void)stopAnimationAndSaveState:(_Bool)arg1;
- (void)startAnimation;
- (void)startRedCircleAnimation;
- (void)startBlackBorderAnimation;
- (void)startProgressAnimation;
- (void)startGradientAnimation;
- (void)prepareLensImageView;
- (void)setAlpha:(double)arg1;
- (void)prepareLayers;
- (id)initWithFrame:(struct CGRect)arg1 maxRecordingLength:(double)arg2;

@end

