//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCChatCellBaseGestureDelegate.h"
#import "SCChatCellStackGestureDelegate.h"
#import "SCChatCellURLLinkGestureDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"

@protocol SCChatCellGestureDelegate <SCChatCellBaseGestureDelegate, SCChatCellURLLinkGestureDelegate, SKStoreProductViewControllerDelegate, SCChatCellStackGestureDelegate>
@end

