//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCChatBrowseMediaBlockingViewDelegate.h"

@class NSString, SCBaseChatMedia, SCChatBrowseMediaBlockingView, UIImageView;

@interface SCChatBrowseImageView : UIView <SCChatBrowseMediaBlockingViewDelegate>
{
    SCBaseChatMedia *_media;
    UIImageView *_imageView;
    SCChatBrowseMediaBlockingView *_blockingView;
    unsigned long long _numberOfRetriedToLoad;
}

- (void).cxx_destruct;
- (void)didClickRetryInMediaBlockingView;
- (void)_loadImageFromMedia;
- (void)setForMedia:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

