//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ASIdentifierManager, NSArray, NSDictionary, NSMutableDictionary, NSString, SCChunkItem, SCDiscoverChannel, SCDiscoverChunk, SCDiscoverEdition, SCDiscoverEditionSession;

@interface SCDiscoverLogger : NSObject
{
    NSString *_snapcodePublisherId;
    NSString *_snapcodeDSnapId;
    NSString *_snapcodeEditionId;
    NSString *_snapcodeActionId;
    NSString *_snapcodeDenyReason;
    _Bool _snapcodeWasConsumed;
    SCDiscoverEditionSession *_currentEditionSession;
    SCDiscoverChannel *_currentChannel;
    SCDiscoverEdition *_currentEdition;
    NSArray *_currentChunks;
    SCDiscoverChunk *_lastViewedLoadingChunk;
    NSDictionary *_currentChunkDict;
    NSMutableDictionary *_currentChunksAdSlots;
    NSString *_editionSessionId;
    id _currentItem;
    double _currentItemStartViewTime;
    SCChunkItem *_currentSharedItem;
    double _currentSharedItemTimeViewed;
    ASIdentifierManager *_asIdentifierManager;
}

+ (void)_setSharingMediaType:(id)arg1 forEvent:(id)arg2;
+ (id)shared;
@property(retain, nonatomic) ASIdentifierManager *asIdentifierManager; // @synthesize asIdentifierManager=_asIdentifierManager;
@property(nonatomic) double currentSharedItemTimeViewed; // @synthesize currentSharedItemTimeViewed=_currentSharedItemTimeViewed;
@property(nonatomic) SCChunkItem *currentSharedItem; // @synthesize currentSharedItem=_currentSharedItem;
@property(nonatomic) double currentItemStartViewTime; // @synthesize currentItemStartViewTime=_currentItemStartViewTime;
@property(retain, nonatomic) id currentItem; // @synthesize currentItem=_currentItem;
@property(copy, nonatomic) NSString *editionSessionId; // @synthesize editionSessionId=_editionSessionId;
@property(retain, nonatomic) NSMutableDictionary *currentChunksAdSlots; // @synthesize currentChunksAdSlots=_currentChunksAdSlots;
@property(retain, nonatomic) NSDictionary *currentChunkDict; // @synthesize currentChunkDict=_currentChunkDict;
@property(retain, nonatomic) SCDiscoverChunk *lastViewedLoadingChunk; // @synthesize lastViewedLoadingChunk=_lastViewedLoadingChunk;
@property(retain, nonatomic) NSArray *currentChunks; // @synthesize currentChunks=_currentChunks;
@property(retain, nonatomic) SCDiscoverEdition *currentEdition; // @synthesize currentEdition=_currentEdition;
@property(retain, nonatomic) SCDiscoverChannel *currentChannel; // @synthesize currentChannel=_currentChannel;
@property(nonatomic) __weak SCDiscoverEditionSession *currentEditionSession; // @synthesize currentEditionSession=_currentEditionSession;
- (void).cxx_destruct;
- (void)_setMediaTypePropertiesForEvent:(id)arg1;
- (void)_setCommonChunkPropertiesForEvent:(id)arg1 chunk:(id)arg2;
- (void)_setCommonEditionSessionPropertiesForEvent:(id)arg1;
- (void)_setCommonPropertiesForViewEvent:(id)arg1 chunk:(id)arg2 timeViewed:(double)arg3;
- (void)logStoreView;
- (void)logRemoteWebpageViewWithPageLoadCount:(long long)arg1 pageLoadErrorCount:(long long)arg2 loadedOnEntry:(_Bool)arg3 loadedOnExit:(_Bool)arg4 visiblePageLoadTimeSec:(double)arg5;
- (void)logScreenshot;
- (void)logAdSkipWithAdChunk:(id)arg1;
- (void)logLongformVideoViewWithStartedWithCaptionOn:(_Bool)arg1 videoWithCaptionOnTimeViewedSeconds:(double)arg2 videoDurationSeconds:(double)arg3 aspectRatio:(double)arg4 videoInLandscapeModeTimeViewedSeconds:(double)arg5;
- (void)logLocalWebpageViewWithPageHeightTotal:(double)arg1 pageHeightSeen:(double)arg2 inlineVideosTotalCount:(long long)arg3 inlineVideosViewedCount:(unsigned long long)arg4 inlineVideosTotalTimeViewedSec:(double)arg5;
- (void)logTopSnapVideoViewWithFullView:(_Bool)arg1 mediaDisplayTimeSec:(double)arg2 durationSec:(double)arg3;
- (void)logTopSnapImageView;
- (void)_logEditionViewSummary;
- (void)logEditionView;
- (void)_setSharingPropertiesForSharingEvent:(id)arg1 sharingParameters:(id)arg2;
- (void)_setCommonPropertiesForSharingEvent:(id)arg1 chunk:(id)arg2;
- (void)logFinishSavingWithSavingParameters:(id)arg1;
- (void)logDeniedSharing;
- (void)logFinishSharingWithSharingParameters:(id)arg1;
- (void)logBeginSharing;
- (void)logUnsubscribeFromChannelWithPublisherId:(id)arg1 source:(unsigned long long)arg2;
- (void)logSubscribeToChannelWithPublisherId:(id)arg1 source:(unsigned long long)arg2;
- (id)deviceAdvertiserIdString;
- (void)setCommonPropertiesForDeepLinkEvent:(id)arg1 publisherId:(id)arg2 editionId:(id)arg3 dSnapId:(id)arg4 scanActionId:(id)arg5 denyReason:(id)arg6;
- (void)didDismissSnapcode:(unsigned long long)arg1;
- (void)didConsumeSnapcode;
- (void)didProcessSnapcodeWithPublisherId:(id)arg1 editionId:(id)arg2 dSnapId:(id)arg3 actionId:(id)arg4 denyReason:(id)arg5;
- (void)wasDeniedDeepLinkForPublisherId:(id)arg1 editionId:(id)arg2 dSnapId:(id)arg3 reason:(id)arg4;
- (void)setMediaTypeForTopSnapItem:(id)arg1 forEvent:(id)arg2;
- (void)setCommonPropertiesForEvent:(id)arg1 withChunk:(id)arg2;
- (void)setLongformPropertiesForEvent:(id)arg1 chunk:(id)arg2 chunkItem:(id)arg3;
- (void)didFinishViewingItem:(id)arg1 fromSection:(id)arg2;
- (void)didStartViewingItem:(id)arg1 fromSection:(id)arg2;
- (void)didSaveSection:(id)arg1 parameters:(id)arg2;
- (void)wasDeniedSharingSection:(id)arg1;
- (void)didCompleteSharingSection:(id)arg1 withParameters:(id)arg2;
- (void)didBeginSharingSection:(id)arg1 hasVideo:(_Bool)arg2;
- (void)didFinishViewingInlineVideoWithID:(id)arg1 fromSection:(id)arg2 timeViewed:(double)arg3 mediaDisplayedTime:(double)arg4 totalVideoDuration:(double)arg5 fullscreenTime:(double)arg6 inlineTime:(double)arg7 startedWithCaptionOn:(_Bool)arg8 videoAspectRatio:(double)arg9 videoInLandscapeModeTimeViewed:(double)arg10 videoWithCaptionOnTimeViewed:(double)arg11;
- (void)didFinishViewingEdition:(id)arg1 fromChannel:(id)arg2 withExitType:(id)arg3;
- (void)didStartViewingEdition:(id)arg1 fromChannel:(id)arg2 context:(unsigned long long)arg3 sessionID:(id)arg4;
- (void)logDiscoverViewWithChannelsSeen:(id)arg1 totalChannelsCount:(long long)arg2 sortOrderId:(id)arg3;
- (void)reset;

@end

