//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCDiscoverFullStackViewController, SCDiscoverSubscribeView;

@protocol SCDiscoverFullStackViewControllerDelegate <NSObject>
- (void)fullStackViewControllerDidSwipeUpToSubscribe;
- (void)horizontalIconInFullStackViewControllerWithCompletion:(void (^)(UIImage *))arg1;
- (_Bool)fullStackViewControllerShouldAllowSubscription;
- (void)fullStackViewControllerDidSetupSubscribeView:(SCDiscoverSubscribeView *)arg1;
- (void)fullStackVideoDidExitInlineVideo;
- (void)fullStackViewControllerDidDismissAppInstall:(SCDiscoverFullStackViewController *)arg1;
- (void)fullStackViewControllerDidPresentAppInstall:(SCDiscoverFullStackViewController *)arg1;
- (void)didTapTopSnapInFullStackViewController:(SCDiscoverFullStackViewController *)arg1;
- (void)fullStackVideoDidEnterFullscreen:(_Bool)arg1 isInline:(_Bool)arg2;
- (void)didFinishPlayingTopSnapVideoInFullStackViewController:(SCDiscoverFullStackViewController *)arg1;
@end

