//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverOperaPageProvider.h"

@class FBKVOController, NSMutableDictionary, NSString, SCDiscoverEdition, SCDiscoverSubscriptionChecker, SCOperaViewModel;

@interface SCDiscoverEditionOperaDataSource : NSObject <SCDiscoverOperaPageProvider>
{
    NSMutableDictionary *_dsnapIDToViewModelMap;
    NSMutableDictionary *_pageIdToOperaPageMap;
    SCDiscoverEdition *_edition;
    SCOperaViewModel *_editionEndViewModel;
    SCOperaViewModel *_subscriptionViewModel;
    SCDiscoverSubscriptionChecker *_subscriptionChecker;
    FBKVOController *_kvoController;
    SCOperaViewModel *_rootViewModel;
}

+ (void)addGestureToolTipsOverlayForViewModel:(id)arg1;
@property(retain, nonatomic) SCOperaViewModel *rootViewModel; // @synthesize rootViewModel=_rootViewModel;
- (void).cxx_destruct;
- (id)operaLongformPageWithDsnapId:(id)arg1;
- (id)operaPageWithPageId:(id)arg1;
- (void)_updateSubscriptionViewModel;
- (void)_chunkIsLoadingDidChange:(id)arg1 chunk:(id)arg2;
- (_Bool)_isRootChunk:(id)arg1;
- (void)dealloc;
- (id)initWithEdition:(id)arg1 shouldStartWithLongform:(_Bool)arg2 discoverUserProperties:(id)arg3 kvoController:(id)arg4;
- (id)initWithEdition:(id)arg1 shouldStartWithLongform:(_Bool)arg2 discoverUserProperties:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

