//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCDiscoverShareControllerDelegate.h"
#import "SCOperaArrowLayerViewControllerDelegate.h"
#import "SCOperaEventListener.h"
#import "SCOperaLocalWebLayerViewControllerDelegate.h"
#import "SCOperaPageViewControllerDelegate.h"
#import "SCOperaPageableViewControllerDelegate.h"
#import "SCPullToDismissVolumeController.h"
#import "SCTimeProfilable.h"
#import "SCVerticalSwipeViewDelegate.h"
#import "SwipeView.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIWebViewDelegate.h"

@class NSMutableArray, NSString, SCChunkItem, SCChunkSection, SCChunkTopSnapItem, SCDiscoverLongformNetworkManipulator, SCDiscoverShareController, SCDiscoverSharedResourceManager, SCDiscoverSubscribeView, SCOperaArrowLayerViewController, SCOperaConfiguration, SCOperaEventListenerAnnouncer, SCOperaLocalWebLayerViewController, SCOperaPage, SCOperaPageViewController, SCOperaRemoteVideoViewController, SCOperaRemoteWebLayerViewController, SCOperaStoreLayerViewController, SCSponsoredSlug, SCSponsoredSlugView, SCUserSession, SCVerticalSwipeView, UIColor, UIImageView, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface SCDiscoverFullStackViewController : UIViewController <UIGestureRecognizerDelegate, UIWebViewDelegate, SCDiscoverShareControllerDelegate, SCTimeProfilable, SCVerticalSwipeViewDelegate, SCOperaLocalWebLayerViewControllerDelegate, SCOperaPageableViewControllerDelegate, SCOperaEventListener, SCOperaPageViewControllerDelegate, SCOperaArrowLayerViewControllerDelegate, SwipeView, SCPullToDismissVolumeController>
{
    UIImageView *_sponsoredSlugImageView;
    UITapGestureRecognizer *_tapToSkipGesture;
    SCSponsoredSlug *_channelSlug;
    SCUserSession *_userSession;
    SCOperaPage *_longformRemoteVideoPage;
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    SCOperaPageViewController *_localWebPageViewController;
    SCOperaLocalWebLayerViewController *_localWebViewController;
    SCOperaPageViewController *_remoteWebPageViewController;
    SCOperaRemoteWebLayerViewController *_remoteWebViewController;
    SCOperaPageViewController *_topSnapPageViewController;
    SCOperaArrowLayerViewController *_arrowLayerViewController;
    SCOperaPageViewController *_storePageViewController;
    SCOperaStoreLayerViewController *_storeViewController;
    SCOperaPageViewController *_subscriptionPageViewController;
    SCDiscoverSubscribeView *_subscribeView;
    SCOperaConfiguration *_configuration;
    _Bool _isSharingVideo;
    _Bool _sharing;
    _Bool _isVisible;
    _Bool _isPartiallyVisible;
    _Bool _isAd;
    id <SCDiscoverFullStackViewControllerDelegate> _delegate;
    SCChunkSection *_section;
    SCChunkItem *_longformItem;
    SCChunkTopSnapItem *_topSnapItem;
    SCOperaRemoteVideoViewController *_remoteVideoViewController;
    SCOperaPageViewController *_longformVideoPageViewController;
    SCVerticalSwipeView *_verticalSwipeView;
    SCDiscoverSharedResourceManager *_sharedResourceManager;
    id <UIViewControllerTransitioningDelegate> _inlineVideoTransitioningDelegate;
    SCDiscoverShareController *_shareController;
    NSMutableArray *_inlineVideos;
    NSString *_adSnapId;
    NSString *_dSnapId;
    NSString *_editionID;
    UIColor *_primaryPublisherColor;
    NSString *_publisherDisplayName;
    NSString *_publisherUniqueName;
    NSString *_publisherName;
    UIColor *_secondaryPublisherColor;
    SCSponsoredSlugView *_slugView;
    UITapGestureRecognizer *_inlineVideoTapRecognizer;
    UIPanGestureRecognizer *_dismissPanRecognizer;
    UIView *_blackView;
    UITapGestureRecognizer *_tapToOpenInlineVideoRecognizer;
    UIView *_screenshotHidingView;
}

+ (long long)context;
+ (id)profiledSelectorNames;
@property(retain, nonatomic) UIView *screenshotHidingView; // @synthesize screenshotHidingView=_screenshotHidingView;
@property(retain, nonatomic) UITapGestureRecognizer *tapToOpenInlineVideoRecognizer; // @synthesize tapToOpenInlineVideoRecognizer=_tapToOpenInlineVideoRecognizer;
@property(retain, nonatomic) UIView *blackView; // @synthesize blackView=_blackView;
@property(retain, nonatomic) UIPanGestureRecognizer *dismissPanRecognizer; // @synthesize dismissPanRecognizer=_dismissPanRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *inlineVideoTapRecognizer; // @synthesize inlineVideoTapRecognizer=_inlineVideoTapRecognizer;
@property(retain, nonatomic) SCSponsoredSlugView *slugView; // @synthesize slugView=_slugView;
@property(nonatomic) _Bool isAd; // @synthesize isAd=_isAd;
@property(retain, nonatomic) UIColor *secondaryPublisherColor; // @synthesize secondaryPublisherColor=_secondaryPublisherColor;
@property(copy, nonatomic) NSString *publisherName; // @synthesize publisherName=_publisherName;
@property(copy, nonatomic) NSString *publisherUniqueName; // @synthesize publisherUniqueName=_publisherUniqueName;
@property(copy, nonatomic) NSString *publisherDisplayName; // @synthesize publisherDisplayName=_publisherDisplayName;
@property(retain, nonatomic) UIColor *primaryPublisherColor; // @synthesize primaryPublisherColor=_primaryPublisherColor;
@property(copy, nonatomic) NSString *editionID; // @synthesize editionID=_editionID;
@property(copy, nonatomic) NSString *dSnapId; // @synthesize dSnapId=_dSnapId;
@property(copy, nonatomic) NSString *adSnapId; // @synthesize adSnapId=_adSnapId;
@property(retain, nonatomic) NSMutableArray *inlineVideos; // @synthesize inlineVideos=_inlineVideos;
@property(retain, nonatomic) SCDiscoverShareController *shareController; // @synthesize shareController=_shareController;
@property(retain, nonatomic) id <UIViewControllerTransitioningDelegate> inlineVideoTransitioningDelegate; // @synthesize inlineVideoTransitioningDelegate=_inlineVideoTransitioningDelegate;
@property(retain, nonatomic) SCDiscoverSharedResourceManager *sharedResourceManager; // @synthesize sharedResourceManager=_sharedResourceManager;
@property(retain, nonatomic) SCVerticalSwipeView *verticalSwipeView; // @synthesize verticalSwipeView=_verticalSwipeView;
@property(retain, nonatomic) SCOperaPageViewController *longformVideoPageViewController; // @synthesize longformVideoPageViewController=_longformVideoPageViewController;
@property(retain, nonatomic) SCOperaRemoteVideoViewController *remoteVideoViewController; // @synthesize remoteVideoViewController=_remoteVideoViewController;
@property(retain, nonatomic) SCOperaRemoteWebLayerViewController *remoteWebViewController; // @synthesize remoteWebViewController=_remoteWebViewController;
@property(retain, nonatomic) SCOperaLocalWebLayerViewController *localWebViewController; // @synthesize localWebViewController=_localWebViewController;
@property(nonatomic) _Bool isPartiallyVisible; // @synthesize isPartiallyVisible=_isPartiallyVisible;
@property(nonatomic) _Bool isVisible; // @synthesize isVisible=_isVisible;
@property(retain, nonatomic) SCChunkTopSnapItem *topSnapItem; // @synthesize topSnapItem=_topSnapItem;
@property(retain, nonatomic) SCChunkItem *longformItem; // @synthesize longformItem=_longformItem;
@property(nonatomic, getter=isSharing) _Bool sharing; // @synthesize sharing=_sharing;
@property(retain, nonatomic) SCChunkSection *section; // @synthesize section=_section;
@property(nonatomic) __weak id <SCDiscoverFullStackViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)arrowLayerViewControllerDidTap:(id)arg1;
- (void)pageViewControllerDidFinishPlaying:(id)arg1;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (void)verticalSwipeView:(id)arg1 bottomSubviewDidBecomeVisible:(_Bool)arg2 offsetEnabled:(_Bool)arg3;
- (_Bool)pageIsPartiallyVisible:(id)arg1;
- (_Bool)pageIsFullyVisible:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
@property(readonly, nonatomic) SCDiscoverLongformNetworkManipulator *longformNetworkManipulator;
- (void)shareControllerDidSaveSnap:(id)arg1 parameters:(id)arg2;
- (void)shareController:(id)arg1 didCompleteSharing:(_Bool)arg2 withParameters:(id)arg3;
- (void)shareControllerDidBeginSharing:(id)arg1;
- (void)shareWithShareableMedias:(id)arg1 touchOrigin:(struct CGPoint)arg2 shareFrameMedia:(id)arg3 linkToLongform:(_Bool)arg4 rotationEnabled:(_Bool)arg5 savingDisabled:(_Bool)arg6;
- (void)didLongPressWithContext:(id)arg1 params:(id)arg2;
- (_Bool)isScrolling;
- (_Bool)isCurrentlyAtTopOfTopSnapItem;
- (_Bool)isCurrentlyViewingTopSnapItem;
- (void)bottomSubviewScrollViewDidEndScrollingAnimation:(id)arg1;
- (void)bottomSubviewScrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)bottomSubviewScrollViewDidEndDecelerating:(id)arg1;
- (void)verticalSwipeView:(id)arg1 didChangePageIndex:(unsigned long long)arg2;
- (void)_setAccessibilityLabelForLongformPage:(id)arg1;
- (void)setupRemoteWebViewControllerForItem:(id)arg1;
- (void)hideSubscribeView;
- (void)remoteWebpageViewDidDisappear:(_Bool)arg1;
- (void)localWebpageViewDidDisappear;
- (void)localWebLayerViewControllerDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)didCreateRequestForURL:(id)arg1;
- (void)setupSubscribeView;
- (void)setupLocalWebViewControllerForItem:(id)arg1;
- (void)appInstallViewDidDisappear:(_Bool)arg1;
- (void)appInstallViewDidAppear:(_Bool)arg1;
- (void)setupAppInstallViewControllerForItem:(id)arg1;
- (void)rotateVideoBasedOnOrientation;
- (_Bool)isViewingRemoteVideo;
- (_Bool)isViewingLongformVideo;
- (_Bool)isViewingInlineVideo;
- (void)longformVideoPlayerDidDisappear;
- (void)longformVideoPlayerDidAppear;
- (id)operaConfiguration;
- (id)operaProperties;
- (id)remoteVideoLayerViewController;
- (void)setupLongformVideoViewForItem:(id)arg1;
- (void)_longformSubscriptionViewDidAppear;
- (void)setupLongformSubscriptionView;
- (void)pauseTopSnapVideo;
- (void)playTopSnapVideo;
- (void)didTapToSkip:(id)arg1;
- (void)setupChannelSponsorSlugView;
- (void)setupLongformChannel:(id)arg1;
- (unsigned long long)horizontalSlugAlignment:(long long)arg1;
- (unsigned long long)verticalSlugAlignment:(long long)arg1;
- (id)overlayControllerWithClass:(Class)arg1 fromControllers:(id)arg2;
- (void)copyCommonSponsoredSlugProperties:(id)arg1 to:(id)arg2;
- (void)setupTopSnapChannel:(id)arg1;
- (void)setupChannels;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidPartiallyAppear;
- (void)viewCannotAppear;
- (void)viewCanAppear;
- (void)viewDidFullyDisappear:(_Bool)arg1;
- (void)viewDidFullyDisappear;
- (void)viewDidFullyAppear;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)setVolume:(double)arg1;
- (void)scrollToLongform:(_Bool)arg1;
- (void)setupVerticalSwipeView;
- (void)loadView;
- (id)initWithSection:(id)arg1 sharedResourceManager:(id)arg2 channelProperties:(id)arg3 userSession:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

