//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCCustomVolumeControllerDelegate.h"
#import "SCDiscoverFullStackViewControllerDelegate.h"
#import "SCDiscoverLoadingViewDelegate.h"
#import "SCTimeProfilable.h"
#import "SCViewControllerTransitionAnimatorDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class CADisplayLink, CALayer, FBKVOController, NSDictionary, NSMutableArray, NSMutableSet, NSString, SCCustomVolumeController, SCDiscoverEdition, SCDiscoverFullStackViewController, SCDiscoverGestureOverlayView, SCDiscoverLoadingView, SCDiscoverSharedResourceManager, SCDiscoverSubscribeView, SCOperaEventListenerAnnouncer, SCPullToDismissEffectHandler, SCUserSession, UIColor, UIImage, UIPanGestureRecognizer, UIScrollView, UITapGestureRecognizer, UIView;

@interface SCDiscoverEditionViewController : UIViewController <SCDiscoverLoadingViewDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, SCDiscoverFullStackViewControllerDelegate, SCCustomVolumeControllerDelegate, SCTimeProfilable, SCViewControllerTransitionAnimatorDelegate>
{
    _Bool _lockForwardScroll;
    CADisplayLink *_scrollViewDisplayLink;
    SCUserSession *_userSession;
    _Bool _didTapToFinish;
    SCDiscoverSubscribeView *_subscribeView;
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    _Bool _shouldStartWithLongform;
    _Bool _hidesStatusBarWhenDismissed;
    _Bool _viewIsBackgrounded;
    _Bool _useChannelLoadingIcon;
    _Bool _isDismissingGestureOverlay;
    _Bool _isUsingNewAnimations;
    id <SCDiscoverEditionViewControllerDelegate> _delegate;
    UIImage *_currentChannelIcon;
    SCDiscoverEdition *_edition;
    CALayer *_iconToHideLayer;
    SCDiscoverSharedResourceManager *_sharedResourceManager;
    UIScrollView *_scrollView;
    unsigned long long _lastPageIndex;
    SCCustomVolumeController *_customVolumeController;
    NSMutableSet *_loadedSectionsSet;
    UIView *_overlay;
    UIColor *_primaryPublisherColor;
    UIColor *_secondaryPublisherColor;
    UIView *_blackOverlayView;
    NSMutableArray *_fullStackVCs;
    SCDiscoverFullStackViewController *_partiallyVisibleFullStackVC;
    SCDiscoverFullStackViewController *_visibleFullStackVC;
    SCDiscoverLoadingView *_leftLoadingView;
    SCDiscoverLoadingView *_rightLoadingView;
    NSMutableSet *_viewedPagesDsnapIDs;
    NSDictionary *_leftLoadingDSnapChunkDict;
    NSDictionary *_rightLoadingDSnapChunkDict;
    SCDiscoverGestureOverlayView *_gestureTutorialOverlay;
    UITapGestureRecognizer *_gestureTutorialTapRecognzier;
    UIPanGestureRecognizer *_panGestureRecognizer;
    double _initialPanX;
    unsigned long long _swipeDirection;
    SCPullToDismissEffectHandler *_dismissEffectHandler;
    FBKVOController *_observeController;
    struct CGRect _circleFrame;
}

+ (long long)context;
+ (id)profiledSelectorNames;
@property(readonly, nonatomic) _Bool isUsingNewAnimations; // @synthesize isUsingNewAnimations=_isUsingNewAnimations;
@property(retain, nonatomic) FBKVOController *observeController; // @synthesize observeController=_observeController;
@property(retain, nonatomic) SCPullToDismissEffectHandler *dismissEffectHandler; // @synthesize dismissEffectHandler=_dismissEffectHandler;
@property(nonatomic) unsigned long long swipeDirection; // @synthesize swipeDirection=_swipeDirection;
@property(nonatomic) double initialPanX; // @synthesize initialPanX=_initialPanX;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(nonatomic) struct CGRect circleFrame; // @synthesize circleFrame=_circleFrame;
@property(nonatomic) _Bool isDismissingGestureOverlay; // @synthesize isDismissingGestureOverlay=_isDismissingGestureOverlay;
@property(retain, nonatomic) UITapGestureRecognizer *gestureTutorialTapRecognzier; // @synthesize gestureTutorialTapRecognzier=_gestureTutorialTapRecognzier;
@property(retain, nonatomic) SCDiscoverGestureOverlayView *gestureTutorialOverlay; // @synthesize gestureTutorialOverlay=_gestureTutorialOverlay;
@property(retain, nonatomic) NSDictionary *rightLoadingDSnapChunkDict; // @synthesize rightLoadingDSnapChunkDict=_rightLoadingDSnapChunkDict;
@property(retain, nonatomic) NSDictionary *leftLoadingDSnapChunkDict; // @synthesize leftLoadingDSnapChunkDict=_leftLoadingDSnapChunkDict;
@property(retain, nonatomic) NSMutableSet *viewedPagesDsnapIDs; // @synthesize viewedPagesDsnapIDs=_viewedPagesDsnapIDs;
@property(retain, nonatomic) SCDiscoverLoadingView *rightLoadingView; // @synthesize rightLoadingView=_rightLoadingView;
@property(retain, nonatomic) SCDiscoverLoadingView *leftLoadingView; // @synthesize leftLoadingView=_leftLoadingView;
@property(nonatomic) _Bool useChannelLoadingIcon; // @synthesize useChannelLoadingIcon=_useChannelLoadingIcon;
@property(retain, nonatomic) SCDiscoverFullStackViewController *visibleFullStackVC; // @synthesize visibleFullStackVC=_visibleFullStackVC;
@property(retain, nonatomic) SCDiscoverFullStackViewController *partiallyVisibleFullStackVC; // @synthesize partiallyVisibleFullStackVC=_partiallyVisibleFullStackVC;
@property(retain, nonatomic) NSMutableArray *fullStackVCs; // @synthesize fullStackVCs=_fullStackVCs;
@property(nonatomic) _Bool viewIsBackgrounded; // @synthesize viewIsBackgrounded=_viewIsBackgrounded;
@property(retain, nonatomic) UIView *blackOverlayView; // @synthesize blackOverlayView=_blackOverlayView;
@property(readonly, nonatomic) UIColor *secondaryPublisherColor; // @synthesize secondaryPublisherColor=_secondaryPublisherColor;
@property(readonly, nonatomic) UIColor *primaryPublisherColor; // @synthesize primaryPublisherColor=_primaryPublisherColor;
@property(retain, nonatomic) UIView *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) NSMutableSet *loadedSectionsSet; // @synthesize loadedSectionsSet=_loadedSectionsSet;
@property(retain, nonatomic) SCCustomVolumeController *customVolumeController; // @synthesize customVolumeController=_customVolumeController;
@property(nonatomic) unsigned long long lastPageIndex; // @synthesize lastPageIndex=_lastPageIndex;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) SCDiscoverSharedResourceManager *sharedResourceManager; // @synthesize sharedResourceManager=_sharedResourceManager;
@property(nonatomic) _Bool hidesStatusBarWhenDismissed; // @synthesize hidesStatusBarWhenDismissed=_hidesStatusBarWhenDismissed;
@property(nonatomic) CALayer *iconToHideLayer; // @synthesize iconToHideLayer=_iconToHideLayer;
@property(nonatomic) _Bool shouldStartWithLongform; // @synthesize shouldStartWithLongform=_shouldStartWithLongform;
@property(retain, nonatomic) SCDiscoverEdition *edition; // @synthesize edition=_edition;
@property(retain, nonatomic) UIImage *currentChannelIcon; // @synthesize currentChannelIcon=_currentChannelIcon;
@property(nonatomic) __weak id <SCDiscoverEditionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getPageViewName;
- (unsigned long long)supportedInterfaceOrientations;
- (void)channelSubscriptionDidUpdate;
- (void)_performSubscriptionFromSource:(unsigned long long)arg1;
- (void)_didTapSubscriptionButton;
- (_Bool)fullStackViewControllerShouldAllowSubscription;
- (void)fullStackViewControllerDidSwipeUpToSubscribe;
- (void)horizontalIconInFullStackViewControllerWithCompletion:(CDUnknownBlockType)arg1;
- (void)fullStackViewControllerDidSetupSubscribeView:(id)arg1;
- (void)fullStackVideoDidExitInlineVideo;
- (void)fullStackViewControllerDidDismissAppInstall:(id)arg1;
- (void)fullStackViewControllerDidPresentAppInstall:(id)arg1;
- (void)topSnapAutoAdvance:(id)arg1 animated:(_Bool)arg2;
- (void)didTapTopSnapInFullStackViewController:(id)arg1;
- (void)fullStackVideoDidEnterFullscreen:(_Bool)arg1 isInline:(_Bool)arg2;
- (void)didFinishPlayingTopSnapVideoInFullStackViewController:(id)arg1;
- (id)fullStackViewControllerForSection:(id)arg1;
- (void)setupInitialUserState;
- (void)updateUserState:(id)arg1;
- (void)updateUserStateForNotViewing;
- (void)updateUserStateForBeganViewing;
- (void)updateUserStateForViewingDSnapId:(id)arg1;
- (void)updateUserStateForViewingSection:(id)arg1;
- (void)didStartViewing;
- (void)preCleanUpForEditionDismissWithExitType:(id)arg1 touchEnabled:(_Bool)arg2;
- (void)didFinishViewingWithFinalBounds:(struct CGRect)arg1 editionDismissRegion:(unsigned long long)arg2 exitType:(id)arg3 touchEnabled:(_Bool)arg4;
- (void)didFinishViewingWithExitType:(id)arg1 touchEnabled:(_Bool)arg2;
- (void)didFinishViewingSectionKeepTouchesEnabled:(_Bool)arg1;
- (void)deviceOrientationDidChange;
- (_Bool)shouldDisplayGestureTutorialOverlay;
- (void)dismissGestureTutorialOverlay;
- (void)setupGestureTutorialOverlayForFullStack:(id)arg1 sharingOnly:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)sendViewCanAppearMessagesFromIndex:(long long)arg1;
- (void)sendViewCannotAppearMessagesFromIndex:(long long)arg1;
- (void)fixScrollViewOffsetAfterAppendingLeftView;
- (void)scrollViewDidEndScrollingWithoutAnimation:(id)arg1;
- (_Bool)scrollToSectionAfterSection:(id)arg1 animated:(_Bool)arg2;
- (void)markAsViewedFromSectionVC:(id)arg1 toSectionVC:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)isPanning;
- (void)setFinalCircleFrame:(struct CGRect)arg1;
- (void)didPan:(id)arg1;
- (void)didTapTutorial:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)exitTypeForSwipeDirection:(unsigned long long)arg1;
- (_Bool)viewControllerTransitionAnimatorShouldBeginDismissingWithDirection:(unsigned long long)arg1;
- (void)viewControllerTransitionAnimatorDidFinishDismissing;
- (void)viewControllerTransitionAnimatorDidCancelDismissing;
- (void)viewControllerTransitionAnimatorDidBeginAnimatingToDismiss;
- (void)viewControllerTransitionAnimatorDidBeginDismissing;
- (void)viewControllerTransitionAnimatorDidFinishPresenting;
- (void)loadingViewDidTapToRetry:(id)arg1;
- (void)setDidViewSection:(id)arg1;
- (void)setDidViewLoadingScreenForChunkDict:(id)arg1;
- (void)setLoadingViewForChunkDict:(id)arg1 direction:(long long)arg2;
- (_Bool)isViewingLoadingViewInDirection:(long long)arg1;
- (void)dismissLoadingView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addLoadingViewWithColor:(id)arg1 error:(id)arg2 direction:(long long)arg3;
- (id)resetEdgeConstraintsForFullStackVCInDirection:(long long)arg1;
- (void)addFullStackViewController:(id)arg1 direction:(long long)arg2;
- (void)addChildVCToScrollView:(id)arg1;
- (void)didLoadSection:(id)arg1 direction:(long long)arg2;
- (void)setupNeighboringFullStackViewControllersFromFullStackIndex:(long long)arg1;
- (void)setupFullStackViewControllerInDirection:(long long)arg1;
- (void)setupInitialFullStackViewController;
- (void)removeObservers;
- (void)addObservers;
- (void)didBecomeActive;
- (void)sectionDidFinishLoading:(id)arg1;
- (void)showGestureTutorialIfNecessary;
- (void)setupTutorialTapGestureRecognizer;
- (void)setupPanGestureRecognizer;
- (_Bool)isSharing;
- (void)setupCustomVolumeView;
- (void)setupScrollView;
- (void)setupOverlayView;
- (_Bool)shouldDismissViewControllerLater;
- (_Bool)shouldPopToRootViewControllerLater;
- (void)viewDidFullyDisappear;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillEnterForeground;
- (void)viewDidEnterBackground;
- (void)loadView;
- (void)dealloc;
- (id)initWithEdition:(id)arg1 channelProperties:(id)arg2 userSession:(id)arg3 eventAnnouncer:(id)arg4 isUsingNewAnimations:(_Bool)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

