//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverEditionViewControllerDelegate.h"
#import "SCDiscoverFullScreenLoadingViewDelegate.h"
#import "SCOperaEventListener.h"
#import "SCOperaLoadingLayerViewDelegate.h"
#import "SCPullToDismissControllerGestureDelegate.h"
#import "SCTimeProfilable.h"
#import "SCViewControllerTransitionAnimatorDelegate.h"

@class CALayer, NSMutableDictionary, NSString, SCDeepLinkURL, SCDiscoverChannel, SCDiscoverChannels, SCDiscoverChannelsModel, SCDiscoverEditionOperaDataSource, SCDiscoverEditionSession, SCDiscoverEditionViewController, SCDiscoverFullScreenLoadingView, SCDiscoverUserProperties, SCOperaEventListenerAnnouncer, SCOperaLoadingLayerView, SCOperaViewController, SCPullToDismissController, SCTileView, SCUserSession, SCViewControllerTransitionAnimator, UIImage, UIView, UIViewController;

@interface SCDiscoverEditionPresenter : NSObject <SCDiscoverEditionViewControllerDelegate, SCDiscoverFullScreenLoadingViewDelegate, SCPullToDismissControllerGestureDelegate, SCTimeProfilable, SCOperaEventListener, SCOperaLoadingLayerViewDelegate, SCViewControllerTransitionAnimatorDelegate>
{
    unsigned long long _context;
    unsigned long long _channelIndex;
    SCDiscoverEditionViewController *_editionViewController;
    SCDiscoverChannel *_currentChannel;
    CDUnknownBlockType _tileDismissalCompletion;
    UIView *_animationCircle;
    CALayer *_currentCellLayer;
    double _defaultFinalChannelDiameter;
    _Bool _editionInitialViewedState;
    SCDiscoverChannels *_channels;
    SCDiscoverChannelsModel *_channelsModel;
    SCTileView *_tileView;
    struct CGPoint _origin;
    SCViewControllerTransitionAnimator *_tileTransitionAnimator;
    UIImage *_currentChannelIcon;
    SCDiscoverFullScreenLoadingView *_operaOffFullScreenLoadingView;
    NSMutableDictionary *_loadingLayerProperties;
    SCOperaLoadingLayerView *_operaOnFullScreenLoadingView;
    SCPullToDismissController *_fullScreenDismissController;
    NSString *_linkedPublisher;
    NSString *_linkedEditionId;
    NSString *_linkedDSnapId;
    unsigned long long _linkedContext;
    SCDeepLinkURL *_deepLinkURL;
    NSString *_deepLinkId;
    _Bool _validatingDsnapToPresent;
    CDUnknownBlockType _validationSuccessBlock;
    SCUserSession *_userSession;
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    SCDiscoverUserProperties *_discoverUserProperties;
    SCDiscoverEditionSession *_editionSession;
    SCOperaViewController *_operaViewController;
    SCPullToDismissController *_operaDismissController;
    SCDiscoverEditionOperaDataSource *_operaEditionDataSource;
    _Bool _shouldStartWithLongform;
    id <SCDiscoverEditionPresenterDelegate> _delegate;
    UIViewController *_presentingViewController;
}

+ (long long)context;
+ (id)profiledSelectorNames;
@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
@property(nonatomic) unsigned long long context; // @synthesize context=_context;
@property(nonatomic) _Bool shouldStartWithLongform; // @synthesize shouldStartWithLongform=_shouldStartWithLongform;
@property(nonatomic) __weak id <SCDiscoverEditionPresenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)editionViewController:(id)arg1 didFinishViewingEdition:(id)arg2 withFinalBounds:(struct CGRect)arg3 editionDismissRegion:(unsigned long long)arg4 exitType:(id)arg5;
- (void)editionViewController:(id)arg1 didFinishViewingEdition:(id)arg2 withExitType:(id)arg3;
- (void)viewControllerTransitionAnimatorDidFinishDismissing;
- (void)viewControllerTransitionAnimatorDidBeginAnimatingToDismiss;
- (void)viewControllerTransitionAnimatorDidCancelDismissing;
- (void)viewControllerTransitionAnimatorDidBeginDismissing;
- (_Bool)viewControllerTransitionAnimatorShouldBeginDismissingWithDirection:(unsigned long long)arg1;
- (void)viewControllerTransitionAnimatorDidFinishPresenting;
- (_Bool)_isAnimatingFromTile;
- (void)_animateChannelForStart:(_Bool)arg1 withFinalBounds:(struct CGRect)arg2 editionDismissRegion:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)presentUsingNewAnimationsWithChildVC:(id)arg1 delegate:(id)arg2;
- (void)_startAnimationAtCellOrigin:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)willEnterForeground:(_Bool)arg1;
- (void)didEnterBackground;
- (_Bool)shouldTriggerPullToDismissWithSwipeDirection:(unsigned long long)arg1;
- (void)loadingLayerViewDidPressErrorButton:(id)arg1;
- (void)fullScreenLoadingViewDidTapToRetry:(id)arg1;
- (id)prepareLinkedEditionForPublisher:(id)arg1 editionId:(id)arg2 dSnapId:(id)arg3 linkableState:(unsigned long long)arg4 chunkDictionary:(id)arg5 isAd:(_Bool)arg6 shouldStartWithLongform:(_Bool)arg7 context:(unsigned long long)arg8;
- (void)teardownFullScreenLoadingView;
- (void)fadeOutFullScreenLoadingView;
- (void)cancelFullScreenLoading;
- (void)setupFullScreenLoadingViewWithImage:(id)arg1 channel:(id)arg2 dSnapId:(id)arg3 circleFrame:(struct CGRect)arg4 circleLayer:(id)arg5;
- (CDUnknownBlockType)validationFailureBlock:(id)arg1 editionId:(id)arg2 dsnapId:(id)arg3 deepLinkURL:(id)arg4 context:(unsigned long long)arg5 successBlock:(CDUnknownBlockType)arg6;
- (void)_wasDeniedDeepLinkingForPublisherId:(id)arg1 editionId:(id)arg2 dSnapId:(id)arg3 availability:(unsigned long long)arg4;
- (void)_validateLinkedEditionForPublisher:(id)arg1 editionId:(id)arg2 deepLinkURL:(id)arg3 context:(unsigned long long)arg4 successBlock:(CDUnknownBlockType)arg5;
- (void)validateLinkedEditionForPublisher:(id)arg1 editionId:(id)arg2 dSnapId:(id)arg3 deepLinkURL:(id)arg4 context:(unsigned long long)arg5 successBlock:(CDUnknownBlockType)arg6;
- (void)validateLinkedEditionForPublisher:(id)arg1 editionId:(id)arg2 dSnapId:(id)arg3 deepLinkURL:(id)arg4 context:(unsigned long long)arg5 circleFrame:(struct CGRect)arg6 circleLayer:(id)arg7 successBlock:(CDUnknownBlockType)arg8;
- (void)updateCurrentCellLayer:(id)arg1 originInPresentingViewFrame:(struct CGPoint)arg2;
- (_Bool)isEditionPresented;
- (void)_dismissEdition;
- (void)dismissEdition;
- (void)_cleanupOperaVC;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (void)resumeEdition;
- (void)pauseEdition;
- (void)_presentOperaViewController;
- (void)_setupOperaViewControllerWithEdition:(id)arg1 channel:(id)arg2;
- (void)_setupEditionViewControllerWithEdition:(id)arg1 channel:(id)arg2;
- (void)_presentEdition:(id)arg1 channelIndex:(unsigned long long)arg2;
- (_Bool)_shouldPresentEdition:(id)arg1;
- (void)presentEditionFromCircle:(id)arg1 fromCellLayer:(id)arg2 cellOriginInPresentingViewFrame:(struct CGPoint)arg3 channelIndex:(unsigned long long)arg4;
- (void)presentEditionFromTile:(id)arg1 withTileView:(id)arg2 channelIndex:(unsigned long long)arg3;
- (_Bool)_shouldUseNewCircleTransition;
- (id)initWithPresentingViewController:(id)arg1 channelsModel:(id)arg2 userSession:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

