//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverSession.h"

@class NSArray, NSDictionary, NSNotificationCenter, NSSet, NSString, SCDiscoverAdSession, SCDiscoverChannel, SCDiscoverChunk, SCDiscoverEdition, SCDiscoverLogger, SCDiscoverRemoteVideoSession, SCDiscoverSharingSession, SCDiscoverSubscriptionSession, SCDiscoverUserProperties, SCOperaEventListenerAnnouncer, SCOperaViewController, SCRequestManager, SCStopwatch, SCUserSession;

@interface SCDiscoverEditionSession : NSObject <SCDiscoverSession>
{
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    SCDiscoverLogger *_logger;
    SCStopwatch *_sessionStopwatch;
    NSSet *_topSnapsViewed;
    NSSet *_longformViewed;
    NSSet *_loadingScreensViewed;
    NSDictionary *_currentPageContext;
    SCStopwatch *_pageViewStopwatch;
    id <SCDiscoverOperaPageProvider> _operaPageProvider;
    SCDiscoverRemoteVideoSession *_remoteVideoSession;
    SCDiscoverAdSession *_adSession;
    SCDiscoverSharingSession *_sharingSession;
    SCDiscoverSubscriptionSession *_subscriptionSession;
    SCRequestManager *_requestManager;
    NSNotificationCenter *_notificationCenter;
    SCDiscoverUserProperties *_discoverUserProperties;
    SCOperaViewController *_operaViewController;
    SCUserSession *_userSession;
    NSString *_sessionID;
    SCDiscoverEdition *_edition;
    SCDiscoverChannel *_channel;
    unsigned long long _context;
    unsigned long long _channelIndex;
    unsigned long long _viewSorting;
    NSString *_sortOrderId;
    NSArray *_chunks;
    NSArray *_adChunks;
    NSString *_deepLinkId;
    double _sessionTimeViewedSec;
    SCDiscoverChunk *_currentChunk;
}

@property(readonly, nonatomic) SCDiscoverChunk *currentChunk; // @synthesize currentChunk=_currentChunk;
@property(readonly, nonatomic) double sessionTimeViewedSec; // @synthesize sessionTimeViewedSec=_sessionTimeViewedSec;
@property(copy, nonatomic) NSString *deepLinkId; // @synthesize deepLinkId=_deepLinkId;
@property(readonly, copy, nonatomic) NSArray *adChunks; // @synthesize adChunks=_adChunks;
@property(readonly, copy, nonatomic) NSArray *chunks; // @synthesize chunks=_chunks;
@property(readonly, copy, nonatomic) NSString *sortOrderId; // @synthesize sortOrderId=_sortOrderId;
@property(readonly, nonatomic) unsigned long long viewSorting; // @synthesize viewSorting=_viewSorting;
@property(readonly, nonatomic) unsigned long long channelIndex; // @synthesize channelIndex=_channelIndex;
@property(readonly, nonatomic) unsigned long long context; // @synthesize context=_context;
@property(readonly, nonatomic) SCDiscoverChannel *channel; // @synthesize channel=_channel;
@property(readonly, nonatomic) SCDiscoverEdition *edition; // @synthesize edition=_edition;
@property(readonly, copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;
- (void)_logDsnapWaitTimeWithContext:(id)arg1 chunk:(id)arg2;
- (void)_logAdSkipIfNecessaryWithContext:(id)arg1 params:(id)arg2;
- (void)_logStoreViewWithContext:(id)arg1 params:(id)arg2;
- (void)_logLongformVideoViewWithContext:(id)arg1 params:(id)arg2;
- (void)_logRemoteWebpageViewWithContext:(id)arg1 params:(id)arg2;
- (void)_logLocalWebpageViewWithContext:(id)arg1 params:(id)arg2;
- (void)_logTopSnapVideoViewWithContext:(id)arg1 params:(id)arg2;
- (void)_logTopSnapImageViewWithContext:(id)arg1 params:(id)arg2;
- (void)_logEditionView;
- (void)userDidTakeScreenshot;
- (void)viewWillEnterForeground;
- (void)viewDidEnterBackground;
- (void)_setRequestManagerDsnapContext:(id)arg1 previousChunk:(id)arg2;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (_Bool)shouldHandleEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (double)pageTimeViewedSec;
- (unsigned long long)lastInteraction;
- (unsigned long long)numLoadingScreensViewed;
- (unsigned long long)numLongformViewed;
- (unsigned long long)numTopSnapsViewed;
- (void)_endSession;
- (void)_beginSession;
- (id)currentLongformVideoId;
- (_Bool)isViewingStore;
- (_Bool)isViewingRemoteWebpage;
- (_Bool)isViewingLongformVideo;
- (_Bool)isViewingLocalWebpage;
- (_Bool)isViewingLongform;
- (_Bool)isViewingTopSnapVideo;
- (_Bool)isViewingTopSnapImage;
- (_Bool)isViewingTopSnap;
- (void)dealloc;
- (id)initWithEventAnnouncer:(id)arg1 edition:(id)arg2 context:(unsigned long long)arg3 channelIndex:(unsigned long long)arg4 viewSorting:(unsigned long long)arg5 sortOrderId:(id)arg6 discoverUserProperties:(id)arg7 operaPageProvider:(id)arg8 userSession:(id)arg9 operaViewController:(id)arg10 sessionStopwatch:(id)arg11 pageViewStopwatch:(id)arg12 adSession:(id)arg13 subscriptionSession:(id)arg14 remoteVideoSession:(id)arg15 sharingSession:(id)arg16 logger:(id)arg17 requestManager:(id)arg18 notificationCenter:(id)arg19;
- (id)initWithEventAnnouncer:(id)arg1 edition:(id)arg2 context:(unsigned long long)arg3 channelIndex:(unsigned long long)arg4 viewSorting:(unsigned long long)arg5 sortOrderId:(id)arg6 discoverUserProperties:(id)arg7 operaPageProvider:(id)arg8 userSession:(id)arg9 operaViewController:(id)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

