//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString, NSURL;

@interface SCDynamicStorySnap : NSObject
{
    int _mediaType;
    NSString *_id;
    NSString *_mediaId;
    NSString *_mediaKey;
    NSString *_mediaIv;
    double _timeLength;
    NSData *_overlayData;
    NSURL *_localMediaUrl;
}

@property(copy, nonatomic) NSURL *localMediaUrl; // @synthesize localMediaUrl=_localMediaUrl;
@property(retain, nonatomic) NSData *overlayData; // @synthesize overlayData=_overlayData;
@property(nonatomic) double timeLength; // @synthesize timeLength=_timeLength;
@property(nonatomic) int mediaType; // @synthesize mediaType=_mediaType;
@property(copy, nonatomic) NSString *mediaIv; // @synthesize mediaIv=_mediaIv;
@property(copy, nonatomic) NSString *mediaKey; // @synthesize mediaKey=_mediaKey;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

