//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLLocation, NSString, SCHydraPerformanceTiming;

@interface SCDynamicStoryRequest : NSObject
{
    SCHydraPerformanceTiming *_performanceTiming;
    NSString *_storyType;
    NSString *_strategy;
    CLLocation *_location;
}

@property(copy, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(readonly, copy, nonatomic) NSString *strategy; // @synthesize strategy=_strategy;
@property(readonly, copy, nonatomic) NSString *storyType; // @synthesize storyType=_storyType;
@property(nonatomic) __weak SCHydraPerformanceTiming *performanceTiming; // @synthesize performanceTiming=_performanceTiming;
- (void).cxx_destruct;
- (CDUnknownBlockType)getDynamicStorySuccessBlockWithCompletion:(CDUnknownBlockType)arg1;
- (void)executeWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithStory:(id)arg1 strategy:(id)arg2;

@end

