//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface SCDynamicStory : NSObject
{
    NSString *_requestId;
    NSArray *_snaps;
}

@property(retain, nonatomic) NSArray *snaps; // @synthesize snaps=_snaps;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
- (void).cxx_destruct;
@property(readonly, nonatomic) double totalTime;
- (id)initWithSnaps:(id)arg1;

@end

