//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCFeatureSettings.h"

@class NSString;

@interface SCFeatureSettings : NSObject <SCFeatureSettings>
{
    _Bool _smartFiltersEnabled;
    _Bool _visualFiltersEnabled;
    _Bool _travelModeEnabled;
    _Bool _payToReplayEnabled;
    _Bool _lensStoreEnabled;
    _Bool _barCodeScanEnabled;
    _Bool _qrCodeScanEnabled;
    _Bool _lensesFaceTrackingVer2Enabled;
    _Bool _lensesFaceTrackingVer2ForInitializationEnabled;
    _Bool _prefetchForStoreEnabled;
    _Bool _lensesActivationTooltipEnabled;
    _Bool _birthdayPartyEnabled;
    _Bool _pendingUpdateToServer;
    _Bool _permissionsEnabled;
    _Bool _galleryEnabled;
    _Bool _galleryInvited;
}

@property(readonly, nonatomic) _Bool galleryInvited; // @synthesize galleryInvited=_galleryInvited;
@property(readonly, nonatomic) _Bool galleryEnabled; // @synthesize galleryEnabled=_galleryEnabled;
@property(readonly, nonatomic) _Bool permissionsEnabled; // @synthesize permissionsEnabled=_permissionsEnabled;
@property(readonly, nonatomic) _Bool pendingUpdateToServer; // @synthesize pendingUpdateToServer=_pendingUpdateToServer;
@property(readonly, nonatomic) _Bool birthdayPartyEnabled; // @synthesize birthdayPartyEnabled=_birthdayPartyEnabled;
@property(readonly, nonatomic) _Bool lensesActivationTooltipEnabled; // @synthesize lensesActivationTooltipEnabled=_lensesActivationTooltipEnabled;
@property(readonly, nonatomic) _Bool prefetchForStoreEnabled; // @synthesize prefetchForStoreEnabled=_prefetchForStoreEnabled;
@property(readonly, nonatomic) _Bool lensesFaceTrackingVer2ForInitializationEnabled; // @synthesize lensesFaceTrackingVer2ForInitializationEnabled=_lensesFaceTrackingVer2ForInitializationEnabled;
@property(readonly, nonatomic) _Bool lensesFaceTrackingVer2Enabled; // @synthesize lensesFaceTrackingVer2Enabled=_lensesFaceTrackingVer2Enabled;
@property(readonly, nonatomic) _Bool qrCodeScanEnabled; // @synthesize qrCodeScanEnabled=_qrCodeScanEnabled;
@property(readonly, nonatomic) _Bool barCodeScanEnabled; // @synthesize barCodeScanEnabled=_barCodeScanEnabled;
@property(readonly, nonatomic) _Bool lensStoreEnabled; // @synthesize lensStoreEnabled=_lensStoreEnabled;
@property(readonly, nonatomic) _Bool payToReplayEnabled; // @synthesize payToReplayEnabled=_payToReplayEnabled;
@property(readonly, nonatomic) _Bool travelModeEnabled; // @synthesize travelModeEnabled=_travelModeEnabled;
@property(readonly, nonatomic) _Bool visualFiltersEnabled; // @synthesize visualFiltersEnabled=_visualFiltersEnabled;
@property(readonly, nonatomic) _Bool smartFiltersEnabled; // @synthesize smartFiltersEnabled=_smartFiltersEnabled;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSmartFiltersEnabled:(_Bool)arg1 visualFiltersEnabled:(_Bool)arg2 travelModeEnabled:(_Bool)arg3 payToReplayEnabled:(_Bool)arg4 lensStoreEnabled:(_Bool)arg5 barCodeScanEnabled:(_Bool)arg6 qrCodeScanEnabled:(_Bool)arg7 lensesFaceTrackingVer2Enabled:(_Bool)arg8 lensesFaceTrackingVer2ForInitializationEnabled:(_Bool)arg9 prefetchForStoreEnabled:(_Bool)arg10 lensesActivationTooltipEnabled:(_Bool)arg11 birthdayPartyEnabled:(_Bool)arg12 pendingUpdateToServer:(_Bool)arg13 permissionsEnabled:(_Bool)arg14 galleryEnabled:(_Bool)arg15 galleryInvited:(_Bool)arg16;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

