//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCFeatureSettings.h"

@interface SCFeatureSettings (Legacy)
+ (void)load;
- (id)initWithCoder_swizzled:(id)arg1;
@end

