//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSURL, SCHydraBluelinksCardController;

@protocol SCHydraBluelinksCardDelegate <NSObject>
- (void)displayBluelinksDebugInfo;
- (void)card:(SCHydraBluelinksCardController *)arg1 loadedSuggestedQueries:(NSArray *)arg2;
- (void)card:(SCHydraBluelinksCardController *)arg1 displayUrl:(NSURL *)arg2;
@end

