//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, SCHydraCardCell;

@protocol SCHydraCardController
@property(nonatomic) __weak id <NSObject> delegate;
- (NSString *)cellTypeIdentifier;
- (void)attachCardView:(SCHydraCardCell *)arg1;
@end

