//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface SCHydraBluelinksSuggestedQuery : NSObject
{
    NSURL *_url;
    NSString *_query;
}

@property(copy, nonatomic) NSString *query; // @synthesize query=_query;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

