//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, SCLoadingIndicatorView, UIImage, UILabel, UIView;

@interface SCHydraCardCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    SCLoadingIndicatorView *_loadingImage;
    UIImage *_image;
    UILabel *_titleLabel;
    id <SCHydraCardViewDelegate> _delegate;
    UIView *_realContentView;
}

@property(readonly, nonatomic) UIView *realContentView; // @synthesize realContentView=_realContentView;
@property(nonatomic) __weak id <SCHydraCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)handleTap:(id)arg1;
- (void)cardErrored:(id)arg1;
- (void)cardFinishedLoading;
@property(copy, nonatomic) NSString *title;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

