//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class AVPlayerLayer, NSString, NSTimer, SCDynamicStory, SCDynamicStorySnap, SCHydraSnapMediaLoader, SCLoadingIndicatorView, SCStoriesTimer, UIImageView, UIView;

@interface SCHydraStoryPlayer : UIViewController <UIGestureRecognizerDelegate>
{
    SCDynamicStorySnap *_currentSnap;
    unsigned long long _numSnaps;
    unsigned long long _index;
    unsigned long long _loadedIndex;
    double _totalTime;
    double _timeLeft;
    _Bool _dismissed;
    _Bool _loading;
    NSTimer *_snapExpiryTimer;
    SCLoadingIndicatorView *_loadingView;
    AVPlayerLayer *_playerLayer;
    UIView *_playerView;
    UIImageView *_imageView;
    SCStoriesTimer *_storiesTimer;
    UIImageView *_overlay;
    SCHydraSnapMediaLoader *_loader;
    SCDynamicStory *_story;
}

@property(retain, nonatomic) SCDynamicStory *story; // @synthesize story=_story;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (void)dismiss;
- (void)previous;
- (void)next;
- (void)imageExpired:(id)arg1;
- (void)itemDidFinishPlaying:(id)arg1;
- (void)viewSwiped:(id)arg1;
- (void)viewTapped:(id)arg1;
- (void)displaySnap:(id)arg1;
- (void)stopLoading;
- (void)startLoading;
- (void)play;
- (void)snapMediaLoaded:(id)arg1 index:(unsigned long long)arg2;
- (void)preloadSnaps;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

