//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCHydraCardController.h"
#import "SCHydraCardViewDelegate.h"

@class NSArray, NSString, SCHydraBluelinksCard, SCHydraBluelinksSuggestedQuery;

@interface SCHydraBluelinksCardController : NSObject <SCHydraCardController, SCHydraCardViewDelegate>
{
    NSArray *_suggestedQueries;
    SCHydraBluelinksSuggestedQuery *_query;
    SCHydraBluelinksCard *_cardView;
    id <SCHydraBluelinksCardDelegate> _delegate;
}

@property(nonatomic) __weak id <SCHydraBluelinksCardDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak SCHydraBluelinksCard *cardView; // @synthesize cardView=_cardView;
@property(retain, nonatomic) SCHydraBluelinksSuggestedQuery *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (void)cardFinishedLoading;
- (void)setQueryWithText:(id)arg1;
- (void)cardWasTapped:(id)arg1;
- (void)setupView;
- (id)cellTypeIdentifier;
- (void)attachCardView:(id)arg1;
- (id)initWithRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

