//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCHydraCardCell.h"

@class UIImage, UIImageView;

@interface SCHydraDynamicStoryCard : SCHydraCardCell
{
    UIImageView *_topSnap;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *topSnapImage;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

