//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCHydraCardController.h"
#import "SCHydraCardViewDelegate.h"

@class NSString, SCHydraBluelinksDebugCard, UIImage;

@interface SCHydraBluelinksDebugCardController : NSObject <SCHydraCardController, SCHydraCardViewDelegate>
{
    UIImage *_image;
    NSString *_text;
    SCHydraBluelinksDebugCard *_cardView;
    id <NSObject> _delegate;
}

@property(nonatomic) __weak id <NSObject> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak SCHydraBluelinksDebugCard *cardView; // @synthesize cardView=_cardView;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)cardFinishedLoading;
- (void)cardWasTapped:(id)arg1;
- (void)setupView;
- (id)cellTypeIdentifier;
- (void)attachCardView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

