//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCHydraPerformanceTiming : NSObject
{
    NSMutableDictionary *_timers;
    NSMutableDictionary *_stats;
}

- (void).cxx_destruct;
- (id)timingDescriptionBetweenEvent:(id)arg1 andEvent:(id)arg2;
- (id)stat:(id)arg1;
- (void)addStat:(id)arg1 value:(id)arg2;
- (void)addEvent:(id)arg1;
- (id)init;

@end

