//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLLocation, NSString, NSURL, NSURLSession, SCHydraPerformanceTiming;

@interface SCHydraBluelinksVisionService : NSObject
{
    NSURL *_endpoint;
    NSString *_base64Image;
    CLLocation *_location;
    struct CGPoint _touchPoint;
    NSURLSession *_urlSession;
    SCHydraPerformanceTiming *_performanceTiming;
    NSString *_requestId;
    NSString *_sessionId;
}

@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(nonatomic) __weak SCHydraPerformanceTiming *performanceTiming; // @synthesize performanceTiming=_performanceTiming;
- (void).cxx_destruct;
- (id)dataByRemovingExif:(id)arg1;
- (id)encodeStringForImage:(id)arg1;
- (id)formattedJSONForRequest;
- (id)parseResponseJSONFromData:(id)arg1;
- (void)executeWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithImage:(id)arg1 location:(id)arg2 touchPoint:(struct CGPoint)arg3 timing:(id)arg4;

@end

