//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCHydraCardController.h"
#import "SCHydraCardViewDelegate.h"

@class NSString, SCDynamicStory, SCHydraDynamicStoryCard, UIImage;

@interface SCHydraDynamicStoryCardController : NSObject <SCHydraCardController, SCHydraCardViewDelegate>
{
    UIImage *_topSnapImage;
    SCHydraDynamicStoryCard *_cardView;
    SCDynamicStory *_story;
    NSString *_title;
    id <SCHydraDynamicStoryCardDelegate> _delegate;
}

@property(nonatomic) __weak id <SCHydraDynamicStoryCardDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) SCDynamicStory *story; // @synthesize story=_story;
@property(nonatomic) __weak SCHydraDynamicStoryCard *cardView; // @synthesize cardView=_cardView;
- (void).cxx_destruct;
- (void)cardFinishedLoading;
- (void)cardWasTapped:(id)arg1;
- (id)getThumbnailImageForVideoURL:(id)arg1 atTime:(double)arg2;
- (id)thumbnailForSnap:(id)arg1;
- (void)setupView;
- (void)loadTopSnap;
- (id)cellTypeIdentifier;
- (void)attachCardView:(id)arg1;
- (id)initWithRequest:(id)arg1 title:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

