//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableArray, NSString, UICollectionView, UICollectionViewFlowLayout, UIImage, UIImageView;

@interface SCHydraHeaderController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource>
{
    UIImageView *_previewImage;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_layout;
    NSMutableArray *_tags;
    id <SCHydraHeaderControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SCHydraHeaderControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSMutableArray *tags; // @synthesize tags=_tags;
- (void).cxx_destruct;
- (id)imageBlendedFromImages:(id)arg1 scaledToSize:(struct CGSize)arg2 withScale:(double)arg3 transform:(struct CGAffineTransform)arg4;
@property(retain, nonatomic) UIImage *image;
- (void)viewDidLayoutSubviews;
- (void)clearTags;
- (void)addTag:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

