//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCHydraViewController.h"

#import "SCHydraBluelinksCardDelegate.h"
#import "SCHydraDynamicStoryCardDelegate.h"
#import "SCHydraHeaderControllerDelegate.h"

@class CLLocation, NSString, SCHydraBluelinksCardController, SCHydraBluelinksDebugCardController, SCHydraBluelinksVisionService, SCHydraCardsController, SCHydraHeaderController, SCHydraPerformanceTiming, UIImage;

@interface SCHydraLaunchViewController : SCHydraViewController <SCHydraDynamicStoryCardDelegate, SCHydraBluelinksCardDelegate, SCHydraHeaderControllerDelegate>
{
    SCHydraHeaderController *_headerController;
    SCHydraCardsController *_cardsController;
    SCHydraPerformanceTiming *_timing;
    SCHydraBluelinksVisionService *_bluelinksVisionService;
    SCHydraBluelinksDebugCardController *_bluelinksDebug;
    UIImage *_image;
    CLLocation *_location;
    struct CGPoint _touchPoint;
    SCHydraBluelinksCardController *_bluelinks;
}

- (void).cxx_destruct;
- (void)displayBluelinksDebugInfo;
- (void)tagWasTapped:(id)arg1;
- (void)card:(id)arg1 loadedSuggestedQueries:(id)arg2;
- (void)card:(id)arg1 displayUrl:(id)arg2;
- (void)card:(id)arg1 displayStory:(id)arg2;
- (void)dismiss;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)downSwipeSucceed;
- (unsigned long long)supportedInterfaceOrientations;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)setImage:(id)arg1 withTouchPoint:(struct CGPoint)arg2 andLocation:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

