//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class SCLoadingIndicatorView, UIImageView, UILabel, UIView;

@interface SCLensCell : UICollectionViewCell
{
    long long _lensCellState;
    UIImageView *_lensIcon;
    UIImageView *_overlayImage;
    SCLoadingIndicatorView *_progressIndicator;
    UIView *_priceOverlay;
    UILabel *_priceLabel;
}

@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UIView *priceOverlay; // @synthesize priceOverlay=_priceOverlay;
@property(retain, nonatomic) SCLoadingIndicatorView *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) UIImageView *overlayImage; // @synthesize overlayImage=_overlayImage;
@property(retain, nonatomic) UIImageView *lensIcon; // @synthesize lensIcon=_lensIcon;
@property(nonatomic) long long lensCellState; // @synthesize lensCellState=_lensCellState;
- (void).cxx_destruct;
- (struct CGRect)getSquareFromSourceRect:(struct CGRect)arg1 itemDimension:(double)arg2;
- (void)setPriceOverlayHidden:(_Bool)arg1;
- (void)setPriceOverlayTransform:(struct CGAffineTransform)arg1;
- (void)setIconTransform:(struct CGAffineTransform)arg1;
- (void)fillViewWithLensIcon:(id)arg1 priceString:(id)arg2 state:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

