//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, SCLowPowerModeExperiment;

@interface SCLowPowerModeController : NSObject
{
    SCLowPowerModeExperiment *_experiment;
    NSDate *_startTime;
    _Bool isAppInLowPowerMode;
}

+ (_Bool)isInitialized;
+ (id)shared;
- (void).cxx_destruct;
- (void)flushEvent;
- (void)showNotification;
- (void)initWithAttemptShowNotification:(_Bool)arg1;
- (id)init;
- (_Bool)shouldSuspendAppEarlier;
- (void)didEnterBackground;
- (void)didBecomeActive;
@property _Bool isAppInLowPowerMode; // @synthesize isAppInLowPowerMode;

@end

