//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString, SCProfileImages, SOJUVerifiedUsersVerifiedSharedPublication;

@interface SCOfficialStory : NSObject <NSCoding>
{
    SOJUVerifiedUsersVerifiedSharedPublication *_story;
    NSString *_snaptag;
    SCProfileImages *_profileImages;
}

+ (id)fastCodingKeys;
@property(readonly, nonatomic) SCProfileImages *profileImages; // @synthesize profileImages=_profileImages;
@property(copy, nonatomic) NSString *snaptag; // @synthesize snaptag=_snaptag;
@property(readonly, nonatomic) SOJUVerifiedUsersVerifiedSharedPublication *story; // @synthesize story=_story;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (_Bool)preferFastCoding;
- (id)initWithPublication:(id)arg1;

@end

