//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class Friend, SCProfilePictureThumbnail, SCScanCardButton, UILabel;

@interface SCScanCardQuickAddTableViewCell : UITableViewCell
{
    Friend *_friend;
    UILabel *_displayNameLabel;
    UILabel *_usernameLabel;
    SCProfilePictureThumbnail *_profilePictureThumbnail;
    SCScanCardButton *_addButton;
    unsigned long long _state;
}

- (void).cxx_destruct;
- (void)_updateButtonToAddedState;
- (void)_didTapAddButton;
- (struct UIEdgeInsets)layoutMargins;
- (id)initWithFriend:(id)arg1;

@end

