//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCScanCardTableViewCell.h"

#import "SCBrowserViewControllerDelegate.h"

@class NSString, NSURL, SCBrowserViewController, UIButton, UIImageView, UILabel, UIView;

@interface SCScanCardQRCode : SCScanCardTableViewCell <SCBrowserViewControllerDelegate>
{
    NSString *_data;
    UIView *_headerCircularBackground;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_openButton;
    UIButton *_cancelButton;
    _Bool _isDataURL;
    NSURL *_dataURL;
    SCBrowserViewController *_browserViewController;
    _Bool _hasUpdatedPageTitle;
    _Bool _hasUpdatedFavicon;
    _Bool _inBrowser;
    NSString *_openButtonTitle;
    UIView *_secondaryTitle;
    double _singleStyleCardHeight;
}

- (void).cxx_destruct;
- (void)didUpdateFavicon:(id)arg1;
- (void)didUpdatePageTitle:(id)arg1;
- (void)didUpdateURL:(id)arg1;
- (void)shouldPresentSafeBrowsingAlert:(id)arg1;
- (void)browserViewIsClosing;
- (void)_didTapCancelButton;
- (void)_didTapOpenButton;
- (void)_didTapHeader;
- (void)_initBrowser;
- (void)_updatePageTitleAndFavicon;
- (void)updateStyle;
- (void)transitionToContentAnimated:(_Bool)arg1;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

