//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCScanCardTableViewCell.h"

@class NSString, SCScanCardDeepLinkData, UIButton, UIImageView, UILabel, UIView;

@interface SCScanCardDiscoverDeepLink : SCScanCardTableViewCell
{
    SCScanCardDeepLinkData *_deepLinkData;
    UILabel *_titleLabel;
    UIView *_headerBackgroundView;
    UIImageView *_imageView;
    UIButton *_openButton;
    UIButton *_cancelButton;
    UIButton *_shareButton;
    UIView *_secondaryHeader;
    NSString *_scanData;
    id <SCScanCardDiscoverDeepLinkDelegate> _deepLinkDelegate;
}

@property(nonatomic) __weak id <SCScanCardDiscoverDeepLinkDelegate> deepLinkDelegate; // @synthesize deepLinkDelegate=_deepLinkDelegate;
- (void).cxx_destruct;
- (void)_didTapOpenButton;
- (void)_didTapShareButton;
- (void)_didTapCancelButton;
- (void)_didTapHeader;
- (void)_updatePreferredSize;
- (void)updateStyle;
- (void)transitionToContentAnimated:(_Bool)arg1;
- (void)loadData;
@property(readonly, nonatomic) UIView *deepLinkIcon;
@property(readonly, nonatomic) struct CGRect deepLinkIconFrame;
- (id)initWithDeepLinkActionData:(id)arg1 scanData:(id)arg2;

@end

