//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCStoryMediaMessage;

@interface SCStoryMediaMessageViewModel : NSObject
{
    SCStoryMediaMessage *_storyMediaMessage;
}

- (void).cxx_destruct;
- (_Bool)shouldDisplayActivityIndicator;
- (_Bool)shouldDisplaySendingOverlay;
- (void)_fetchImageToDisplayWithCompletionHandler:(CDUnknownBlockType)arg1 scaledToSize:(struct CGSize)arg2 userSession:(id)arg3 mediaIndex:(unsigned long long)arg4 images:(id)arg5;
- (void)fetchImagesToDisplayWithCompletionHandler:(CDUnknownBlockType)arg1 scaledToSize:(struct CGSize)arg2 userSession:(id)arg3;
- (_Bool)readyForDisplay;
- (_Bool)anyMediaUploaded;
- (_Bool)isProcessingOrUploadingMedia;
- (_Bool)isLoadingFirstMedia;
- (_Bool)allMediaLoaded;
- (_Bool)firstMediaLoaded;
- (id)mediaList;
- (id)initWithStoryMediaMessage:(id)arg1;

@end

