//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCBatchedMediaMessage.h"

#import "SCBaseMediaMessageUploadingDelegate.h"

@class NSString;

@interface SCStoryMediaMessage : SCBatchedMediaMessage <SCBaseMediaMessageUploadingDelegate>
{
    NSString *_recipientString;
    NSString *_title;
}

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)_recipientStringWithRecipients:(id)arg1;
- (void)baseMediaMessageDidLoseMedia:(id)arg1;
- (void)baseMediaMessageDidFailUpload:(id)arg1;
- (void)baseMediaMessageDidUpload:(id)arg1;
- (id)_failedStoryMessageWithRecipientUserNames:(id)arg1 isFailedToSendToNonFriend:(_Bool)arg2;
- (CDUnknownBlockType)_sendFailureBlock;
- (CDUnknownBlockType)_sendSuccessBlock;
- (void)_send;
- (void)fetchMediaFromIndex:(unsigned long long)arg1 number:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchMoreMediaFromIndex:(unsigned long long)arg1;
- (void)fetchMoreMedia;
- (void)fetchFirstMedia;
- (void)fetchMedia;
- (void)preloadMedia;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUsername:(id)arg1 dictionary:(id)arg2;
- (id)initWithSender:(id)arg1 recipient:(id)arg2;
- (id)initWithSender:(id)arg1 recipients:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

