//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCStackedNoteCollectionViewCell.h"

@class SCChatVideoNoteMediaMessage, SCLoadingIndicatorView, SCVideoNoteView;

@interface SCStackedVideoNoteCollectionViewCell : SCStackedNoteCollectionViewCell
{
    id <SCStackedCollectionViewCellActionDelegate> _delegate;
    SCVideoNoteView *_videoNoteView;
    SCLoadingIndicatorView *_activityIndicatorView;
    SCChatVideoNoteMediaMessage *_message;
}

+ (id)cellReuseIdentifier;
- (void).cxx_destruct;
- (void)_updateVideoNoteView;
- (void)showSpinner:(_Bool)arg1;
- (void)didShowPendingDisplay;
- (void)didShowCompleteDisplay;
- (void)setVideoNoteViewCellIsReadyForDisplay:(_Bool)arg1;
- (void)setIsSender:(_Bool)arg1;
- (void)setMessage:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (_Bool)representsMessage:(id)arg1;
- (void)setVideoNoteViewCellActionDelegate:(id)arg1;
- (void)prepareForReuse;
- (void)stopAnimation;
- (void)startAnimation;
- (void)clearContents;
- (id)activityIndicatorView;
- (void)_initVideoNoteView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

