//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAlertView.h"

@class UIImageView, UIView;

@interface SCStoreAlertView : SCAlertView
{
    UIImageView *_lensImageView;
    UIView *_roundedView;
}

@property(retain, nonatomic) UIView *roundedView; // @synthesize roundedView=_roundedView;
@property(retain, nonatomic) UIImageView *lensImageView; // @synthesize lensImageView=_lensImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1 description:(id)arg2 actions:(id)arg3 lens:(id)arg4 configuration:(CDUnknownBlockType)arg5 dismissHandler:(CDUnknownBlockType)arg6;

@end

