//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSSet, NSString;

@interface SCTabBarLogger : NSObject
{
    NSString *_tapPage;
    NSString *_longPressPage;
    NSDictionary *_pageMap;
    NSSet *_pageMapKeys;
    NSSet *_pageMapValues;
    NSString *_pageViewLogFrom;
    NSString *_pageViewLogTo;
    _Bool _shouldCoalescePageView;
    NSString *_fromPageNormalized;
}

+ (_Bool)shouldLog;
+ (id)shared;
@property(readonly, nonatomic) NSString *fromPageNormalized; // @synthesize fromPageNormalized=_fromPageNormalized;
- (void).cxx_destruct;
- (id)_normalizedTabBarPageNameFrom:(id)arg1;
- (void)_resetActions;
- (void)logOpenQuickChatFromPage:(id)arg1 method:(id)arg2;
- (void)logViewStoryFromPage:(id)arg1 method:(id)arg2;
- (void)logRecordingFromPage:(id)arg1;
- (void)logPageView:(id)arg1 from:(id)arg2 method:(id)arg3;
- (void)_sampleLogEvent:(id)arg1 parameters:(id)arg2;
- (void)didLongPresssFrom:(id)arg1;
- (void)didTapFrom:(id)arg1;
- (void)pageViewChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

