//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCTabBarItemView;

@interface SCTabBarItem : NSObject
{
    _Bool _hidden;
    _Bool _selected;
    long long _itemType;
    double _percentVisible;
    double _alpha;
    long long _badgeCount;
    SCTabBarItemView *_view;
}

@property(retain, nonatomic) SCTabBarItemView *view; // @synthesize view=_view;
@property(nonatomic) long long badgeCount; // @synthesize badgeCount=_badgeCount;
@property(nonatomic) double alpha; // @synthesize alpha=_alpha;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) double percentVisible; // @synthesize percentVisible=_percentVisible;
@property(readonly, nonatomic) long long itemType; // @synthesize itemType=_itemType;
- (void).cxx_destruct;
- (void)updateWithBadgeStyle:(long long)arg1;
- (void)updateInteractiveTransition:(double)arg1;
- (id)initWithItemType:(long long)arg1;

@end

