//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSString, UIScreenEdgePanGestureRecognizer;

@interface SCTabBarView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _staticButtonOrigins;
    NSArray *_items;
    id <SCTabBarViewDelegate> _delegate;
    long long _badgeStyle;
    long long _selectedIndex;
    double _backgroundMaskPercent;
    id <NSObject> _notificationObserver;
    UIView *_backgroundView;
    UIView *_backgroundMaskView;
    double _sideItemCenterOnCameraPage;
    double _sideItemCenterOnSidePage;
    UIScreenEdgePanGestureRecognizer *_screenEdgePanGestureRecognizer;
}

+ (id)oppositePageGradientViewForView:(id)arg1;
+ (_Bool)shouldUseNewTabBar;
+ (void)setDefaultBadgeStyle:(long long)arg1;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *screenEdgePanGestureRecognizer; // @synthesize screenEdgePanGestureRecognizer=_screenEdgePanGestureRecognizer;
@property(nonatomic) double sideItemCenterOnSidePage; // @synthesize sideItemCenterOnSidePage=_sideItemCenterOnSidePage;
@property(nonatomic) double sideItemCenterOnCameraPage; // @synthesize sideItemCenterOnCameraPage=_sideItemCenterOnCameraPage;
@property(retain, nonatomic) UIView *backgroundMaskView; // @synthesize backgroundMaskView=_backgroundMaskView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) id <NSObject> notificationObserver; // @synthesize notificationObserver=_notificationObserver;
@property(nonatomic) double backgroundMaskPercent; // @synthesize backgroundMaskPercent=_backgroundMaskPercent;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) _Bool staticButtonOrigins; // @synthesize staticButtonOrigins=_staticButtonOrigins;
@property(nonatomic) long long badgeStyle; // @synthesize badgeStyle=_badgeStyle;
@property(nonatomic) __weak id <SCTabBarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool areButtonsInCorner;
- (struct CGPoint)centerForItemAtIndex:(long long)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (void)itemTouchUp:(id)arg1;
- (void)itemTapped:(id)arg1;
- (void)itemLongPressed:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

