//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class SCBadgeView, UIImageView, UIView;

@interface SCTabBarItemView : UIControl
{
    UIImageView *_imageView;
    UIImageView *_cameraPageImageView;
    UIImageView *_backgroundImageView;
    UIView *_selectedView;
    SCBadgeView *_badgeCountView;
    UIView *_dotBadgeView;
    long long _badgeStyle;
    long long _badgeCount;
    long long _itemType;
}

+ (void)setOppositeImageView:(id)arg1 itemType:(long long)arg2 isBadged:(_Bool)arg3;
+ (id)selectedImageViewForType:(long long)arg1;
+ (id)notBadgeTintColor;
+ (id)badgeTintColorForType:(long long)arg1;
+ (id)captureTabBarView;
+ (id)storiesTabBarView;
+ (id)chatTabBarView;
@property(nonatomic) long long itemType; // @synthesize itemType=_itemType;
@property(nonatomic) long long badgeCount; // @synthesize badgeCount=_badgeCount;
@property(nonatomic) long long badgeStyle; // @synthesize badgeStyle=_badgeStyle;
@property(retain, nonatomic) UIView *dotBadgeView; // @synthesize dotBadgeView=_dotBadgeView;
@property(retain, nonatomic) SCBadgeView *badgeCountView; // @synthesize badgeCountView=_badgeCountView;
@property(retain, nonatomic) UIView *selectedView; // @synthesize selectedView=_selectedView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIImageView *cameraPageImageView; // @synthesize cameraPageImageView=_cameraPageImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (id)badgeTintColor;
- (id)initializeDotBadgeView;
- (id)initializeBadgeCountView;
- (id)initializeSelectedView;
@property(readonly, nonatomic, getter=isBadged) _Bool badged;
- (void)updateWithBadgeStyle:(long long)arg1;
- (void)updateImageViewsAndLayout;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

