//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class FBKVOController, NSArray, NSString, SCAutoPagingManager, SCTileCoordinator, SCTilesDynamicLayoutCalculator, SCTilesOrganizer, UICollectionView, UICollectionViewFlowLayout, UILongPressGestureRecognizer;

@interface SCTilesCollectionViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate>
{
    UICollectionViewFlowLayout *_layout;
    SCAutoPagingManager *_autoPagingManager;
    SCTileCoordinator *_tileCoordinator;
    NSString *_tappedTileId;
    id <SCTilesCollectionViewControllerDelegate> _delegate;
    SCTilesOrganizer *_tilesOrganizer;
    FBKVOController *_kvoController;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UILongPressGestureRecognizer *_miniProfileLongPressGestureRecognizer;
    struct CGPoint _initialTapPoint;
    unsigned long long _context;
    SCTilesDynamicLayoutCalculator *_dynamicLayoutCalculator;
    _Bool _isScrolling;
    _Bool _shouldReloadCollectionView;
    _Bool _isTappingOrPresentingTile;
    _Bool _isBeingInteracted;
    UICollectionView *_collectionView;
}

@property(nonatomic) _Bool isBeingInteracted; // @synthesize isBeingInteracted=_isBeingInteracted;
@property(readonly, nonatomic) UICollectionViewFlowLayout *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (double)sectionHeight;
- (void)setAllCoversHeadlineAlpha:(double)arg1;
- (id)visibleCellWithTileId:(id)arg1;
- (void)animateCellToTheEndWithTileId:(id)arg1;
- (void)_animateFeaturedSectionCellToTheEndWithTileId:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)reloadCollectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)stopAlternating;
- (void)startAlternating;
- (void)stopAutoPaging;
- (void)resetAutoPaging;
- (void)unshrinkTileView:(id)arg1 animationDuration:(double)arg2 animationOptions:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)unshrinkTileViewWithTileId:(id)arg1;
- (void)shrinkTileView:(id)arg1;
- (void)shrinkTileView:(id)arg1 animationDuration:(double)arg2 scale:(double)arg3 alpha:(double)arg4 animationOptions:(unsigned long long)arg5 completion:(CDUnknownBlockType)arg6;
- (void)presentControllerForTileWithTileId:(id)arg1;
- (void)didLongPressToShowMiniProfile:(id)arg1;
- (void)didLongPress:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_setupGestureRecognizers;
- (void)tileViewModelWithTile:(id)arg1 size:(struct CGSize)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateCell:(id)arg1 withTile:(id)arg2;
- (void)_addIndividualTileObserversWithTiles:(id)arg1;
- (void)fetchMediaInBackground;
@property(copy, nonatomic) NSArray *tiles; // @dynamic tiles;
- (void)_reloadDynamicLayoutIfNecessary;
- (void)moveTileToTheEndWithTileId:(id)arg1;
- (unsigned long long)indexOfTileWithTileId:(id)arg1;
- (unsigned long long)indexOfVisibleCellWithTileId:(id)arg1;
- (void)resetToInitialPosition;
- (void)viewControllerTransitionAnimatorDidFinishDismissing;
- (void)viewControllerTransitionAnimatorDidFinishPresenting;
- (void)_setupCollectionView;
- (void)_setupAutoPaging;
- (void)dealloc;
- (id)initWithLayout:(id)arg1 context:(unsigned long long)arg2 tiles:(id)arg3 delegate:(id)arg4 viewedTilesAtBack:(_Bool)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

