//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer, SCTileCoverViewModel, UIImageView, UILabel;

@interface SCTileCoverView : UIView
{
    CAGradientLayer *_gradientLayer;
    UIImageView *_imageView;
    UILabel *_headlineLabel;
    SCTileCoverViewModel *_cover;
    UIView *_colorOverlay;
}

@property(readonly, nonatomic) UIView *colorOverlay; // @synthesize colorOverlay=_colorOverlay;
@property(retain, nonatomic) SCTileCoverViewModel *cover; // @synthesize cover=_cover;
@property(readonly, nonatomic) UILabel *headlineLabel; // @synthesize headlineLabel=_headlineLabel;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_layoutHeadlineLabel;
- (void)clearContent;
- (id)initWithFrame:(struct CGRect)arg1;

@end

