//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCMediaOwnerProtocol.h"

@class FBKVOController, NSArray, NSString, TMCache;

@interface SCTiles : NSObject <SCMediaOwnerProtocol, NSCoding>
{
    FBKVOController *_kvoController;
    NSArray *_tileIdOrder;
    TMCache *_cache;
    NSArray *_allTiles;
}

+ (id)tileWithTileId:(id)arg1 tiles:(id)arg2;
+ (id)fastCodingKeys;
@property(copy, nonatomic) NSArray *allTiles; // @synthesize allTiles=_allTiles;
@property(retain, nonatomic) TMCache *cache; // @synthesize cache=_cache;
@property(readonly, copy, nonatomic) NSArray *tileIdOrder; // @synthesize tileIdOrder=_tileIdOrder;
- (void).cxx_destruct;
- (void)didDecodeObject;
- (void)setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (_Bool)preferFastCoding;
- (void)refreshTiles;
- (void)ensureNonNilObjects;
- (id)cacheMediaIds;
- (void)clearCache;
- (void)removeExpiredMedia;
- (id)orderedTilesFromTiles:(id)arg1;
- (void)updateWithTileOrderJSON:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

