//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SCTileCoverView, SCTileLoadingView, SCTileViewModel, UIImageView, UILabel;

@interface SCTileView : UIView
{
    _Bool _supportsReadState;
    UIImageView *_readStateCheckMark;
    SCTileViewModel *_tileViewModel;
    UIImageView *_logoImageView;
    UILabel *_logoLabel;
    SCTileCoverView *_coverViewAbove;
    SCTileCoverView *_coverViewBelow;
    SCTileLoadingView *_loadingView;
    UILabel *_sponsoredLabel;
}

@property(readonly, nonatomic) UILabel *sponsoredLabel; // @synthesize sponsoredLabel=_sponsoredLabel;
@property(readonly, nonatomic) SCTileLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(readonly, nonatomic) SCTileCoverView *coverViewBelow; // @synthesize coverViewBelow=_coverViewBelow;
@property(readonly, nonatomic) SCTileCoverView *coverViewAbove; // @synthesize coverViewAbove=_coverViewAbove;
@property(readonly, nonatomic) UILabel *logoLabel; // @synthesize logoLabel=_logoLabel;
@property(readonly, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) SCTileViewModel *tileViewModel; // @synthesize tileViewModel=_tileViewModel;
- (void).cxx_destruct;
- (void)clearContent;
- (void)reset;
- (void)setHeadlineLabelAlpha:(double)arg1;
- (void)setColorOverlayAlpha:(double)arg1;
- (void)setColorOverlayColor:(id)arg1;
- (void)swapCovers;
- (void)setCoverViewsHidden:(_Bool)arg1;
- (void)setLoadingViewVisibility:(_Bool)arg1 withIndicator:(_Bool)arg2 withFadeEffect:(_Bool)arg3;
- (void)_setupReadStateCheckMark;
- (void)_setReadState:(_Bool)arg1;
- (void)updateSponsoredLabel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 hasCornerRadius:(_Bool)arg2 supportsReadState:(_Bool)arg3 coordinator:(id)arg4;

@end

