//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCStoreFeaturedLensDataFetcherDelegate.h"
#import "SCStoreLensControllerDelegate.h"
#import "SCTimeProfilable.h"
#import "SCUnlockFilterControllerDelegate.h"
#import "SCUnlockableDataFetcherDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, SCStoreFeaturedLensDataFetcher, SCStoreLensController, SCUnlockFilterController, SCUnlockableDataFetcher;

@interface SCUnlockableDataStore : NSObject <NSCoding, SCStoreLensControllerDelegate, SCStoreFeaturedLensDataFetcherDelegate, SCUnlockableDataFetcherDelegate, SCUnlockFilterControllerDelegate, SCTimeProfilable>
{
    NSMutableDictionary *_dataStore;
    NSMutableDictionary *_unlockedFilterDataStore;
    NSMutableArray *_pendingVerificationPurchases;
    SCStoreLensController *_storeLensController;
    SCUnlockFilterController *_unlockableFilterController;
    SCStoreFeaturedLensDataFetcher *_featuredLensDataFetcher;
    SCUnlockableDataFetcher *_unlockableDataFetcher;
}

+ (long long)context;
+ (id)profiledSelectorNames;
+ (void)removeSavedState;
+ (id)path;
+ (id)sharedInstance;
@property(retain, nonatomic) SCUnlockableDataFetcher *unlockableDataFetcher; // @synthesize unlockableDataFetcher=_unlockableDataFetcher;
@property(retain, nonatomic) SCStoreFeaturedLensDataFetcher *featuredLensDataFetcher; // @synthesize featuredLensDataFetcher=_featuredLensDataFetcher;
@property(retain, nonatomic) SCUnlockFilterController *unlockableFilterController; // @synthesize unlockableFilterController=_unlockableFilterController;
@property(retain, nonatomic) SCStoreLensController *storeLensController; // @synthesize storeLensController=_storeLensController;
- (void).cxx_destruct;
- (void)setLensIAPAsPendingVerification:(id)arg1;
- (_Bool)isLensIAPPendingVerification:(id)arg1;
- (void)refetchPendingVerificationPurchases;
- (void)inAppPurchaseTransactionDidChange:(id)arg1;
- (void)unlockableDataFetcher:(id)arg1 didFailWithError:(id)arg2;
- (void)unlockableDataFetcher:(id)arg1 didFetchData:(id)arg2;
- (void)storeLensListDataFetcher:(id)arg1 didFailWithError:(id)arg2;
- (void)storeLensListDataFetcher:(id)arg1 didFetchData:(id)arg2;
- (void)unlockFilterController:(id)arg1 didUpdateUnlockedFilterData:(id)arg2;
- (void)storeLensController:(id)arg1 didUpdatePurchasedLensesData:(id)arg2;
- (void)storeLensController:(id)arg1 didUpdateFeaturedLensesData:(id)arg2;
- (_Bool)isLensStoreAvailable;
- (void)_setObject:(id)arg1 forKey:(id)arg2;
- (void)_setFilterObject:(id)arg1 forKey:(id)arg2;
- (id)filterObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
@property(readonly, nonatomic) long long featuredLensesToDisplayCount;
- (void)updateData;
- (void)updateDataIfNecessary;
- (void)_ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)clear;
- (void)saveState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

