//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSArray, NSNumber, NSString;

@protocol SOJUBroadcastBroadcastInitResponse <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSArray *subscriptions;
@property(readonly, copy, nonatomic) NSString *sortOrderId;
@property(readonly, copy, nonatomic) NSString *updatedHashcode;
@property(readonly, copy, nonatomic) NSNumber *updatedTimestamp;
@property(readonly, copy, nonatomic) NSArray *channelOrder;
@end

