//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SOJUAdAppInstallImpressionTrack, SOJUAdLongformVideoImpressionTrack, SOJUAdRemoteWebpageImpressionTrack, SOJUAdThreeVImpressionTrack;

@interface SOJUAdImpressionDataBuilder : NSObject
{
    NSString *_adType;
    SOJUAdThreeVImpressionTrack *_threeV;
    SOJUAdAppInstallImpressionTrack *_appInstall;
    SOJUAdLongformVideoImpressionTrack *_longformVideo;
    SOJUAdRemoteWebpageImpressionTrack *_remoteWebpage;
}

+ (id)withJUAdImpressionData:(id)arg1;
- (void).cxx_destruct;
- (id)setRemoteWebpage:(id)arg1;
- (id)setLongformVideo:(id)arg1;
- (id)setAppInstall:(id)arg1;
- (id)setThreeV:(id)arg1;
- (id)setAdType:(id)arg1;
- (id)build;

@end

