//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString;

@interface SOJUBroadcastBroadcastInitResponseBuilder : NSObject
{
    NSArray *_channelOrder;
    NSNumber *_updatedTimestamp;
    NSString *_updatedHashcode;
    NSString *_sortOrderId;
    NSArray *_subscriptions;
}

+ (id)withJUBroadcastBroadcastInitResponse:(id)arg1;
- (void).cxx_destruct;
- (id)setSubscriptions:(id)arg1;
- (id)setSortOrderId:(id)arg1;
- (id)setUpdatedHashcode:(id)arg1;
- (id)setUpdatedTimestamp:(id)arg1;
- (id)setChannelOrder:(id)arg1;
- (id)build;

@end

