//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUBroadcastBroadcastInitResponse.h"

@class NSArray, NSNumber, NSString;

@interface SOJUBroadcastBroadcastInitResponse : NSObject <SOJUBroadcastBroadcastInitResponse>
{
    NSArray *_channelOrder;
    NSNumber *_updatedTimestamp;
    NSString *_updatedHashcode;
    NSString *_sortOrderId;
    NSArray *_subscriptions;
}

@property(readonly, copy, nonatomic) NSArray *subscriptions; // @synthesize subscriptions=_subscriptions;
@property(readonly, copy, nonatomic) NSString *sortOrderId; // @synthesize sortOrderId=_sortOrderId;
@property(readonly, copy, nonatomic) NSString *updatedHashcode; // @synthesize updatedHashcode=_updatedHashcode;
@property(readonly, copy, nonatomic) NSNumber *updatedTimestamp; // @synthesize updatedTimestamp=_updatedTimestamp;
@property(readonly, copy, nonatomic) NSArray *channelOrder; // @synthesize channelOrder=_channelOrder;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithChannelOrder:(id)arg1 updatedTimestamp:(id)arg2 updatedHashcode:(id)arg3 sortOrderId:(id)arg4 subscriptions:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

