//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"
#import "SOJUAuthPayload.h"

@class NSNumber, NSString;

@protocol SOJUIdentityRegistrationV2Request <NSObject, NSCoding, NSCopying, SOJUAuthPayload>
@property(readonly, copy, nonatomic) NSString *deviceTokenSig;
@property(readonly, copy, nonatomic) NSString *deviceTokenId;
@property(readonly, copy, nonatomic) NSString *piggyBackParam;
@property(readonly, copy, nonatomic) NSString *studySettings;
@property(readonly, copy, nonatomic) NSNumber *fromDeepLink;
@property(readonly, copy, nonatomic) NSString *timeZone;
@property(readonly, copy, nonatomic) NSString *birthday;
@property(readonly, copy, nonatomic) NSString *lastName;
@property(readonly, copy, nonatomic) NSString *firstName;
@property(readonly, copy, nonatomic) NSString *password;
@property(readonly, copy, nonatomic) NSString *username;
@property(readonly, copy, nonatomic) NSString *reqToken;
@property(readonly, copy, nonatomic) NSString *timestamp;
@end

