//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUIdentityRegistrationV2Request.h"

@class NSNumber, NSString;

@interface SOJUIdentityRegistrationV2Request : NSObject <SOJUIdentityRegistrationV2Request>
{
    NSString *_timestamp;
    NSString *_reqToken;
    NSString *_username;
    NSString *_password;
    NSString *_firstName;
    NSString *_lastName;
    NSString *_birthday;
    NSString *_timeZone;
    NSNumber *_fromDeepLink;
    NSString *_studySettings;
    NSString *_piggyBackParam;
    NSString *_deviceTokenId;
    NSString *_deviceTokenSig;
}

@property(readonly, copy, nonatomic) NSString *deviceTokenSig; // @synthesize deviceTokenSig=_deviceTokenSig;
@property(readonly, copy, nonatomic) NSString *deviceTokenId; // @synthesize deviceTokenId=_deviceTokenId;
@property(readonly, copy, nonatomic) NSString *piggyBackParam; // @synthesize piggyBackParam=_piggyBackParam;
@property(readonly, copy, nonatomic) NSString *studySettings; // @synthesize studySettings=_studySettings;
@property(readonly, copy, nonatomic) NSNumber *fromDeepLink; // @synthesize fromDeepLink=_fromDeepLink;
@property(readonly, copy, nonatomic) NSString *timeZone; // @synthesize timeZone=_timeZone;
@property(readonly, copy, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
@property(readonly, copy, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(readonly, copy, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(readonly, copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, copy, nonatomic) NSString *reqToken; // @synthesize reqToken=_reqToken;
@property(readonly, copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTimestamp:(id)arg1 reqToken:(id)arg2 username:(id)arg3 password:(id)arg4 firstName:(id)arg5 lastName:(id)arg6 birthday:(id)arg7 timeZone:(id)arg8 fromDeepLink:(id)arg9 studySettings:(id)arg10 piggyBackParam:(id)arg11 deviceTokenId:(id)arg12 deviceTokenSig:(id)arg13;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

