//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUSponsoredSlugPosAndText.h"

@interface SOJUSponsoredSlugPosAndText (Getter)
- (_Bool)slugRemainsAfterPulsingValue;
- (float)pulseViewBackgroundOpacityValue;
- (long long)pulseBreakDurationMillisValue;
- (long long)pulseDurationMillisValue;
- (int)pulsesCountValue;
- (float)pulseViewStartingOpacityValue;
- (int)longformTimeBeforeFadeoutValue;
- (int)timeBeforeFadeoutValue;
- (long long)positionEnum;
- (long long)alignmentEnum;
@end

