//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUSponsoredSlugPosAndTextBuilder.h"

@interface SOJUSponsoredSlugPosAndTextBuilder (Setter)
- (id)setSlugRemainsAfterPulsingValue:(_Bool)arg1;
- (id)setPulseViewBackgroundOpacityValue:(float)arg1;
- (id)setPulseBreakDurationMillisValue:(long long)arg1;
- (id)setPulseDurationMillisValue:(long long)arg1;
- (id)setPulsesCountValue:(int)arg1;
- (id)setPulseViewStartingOpacityValue:(float)arg1;
- (id)setLongformTimeBeforeFadeoutValue:(int)arg1;
- (id)setTimeBeforeFadeoutValue:(int)arg1;
- (id)setPositionEnum:(long long)arg1;
- (id)setAlignmentEnum:(long long)arg1;
@end

